### ISSUE TITLE
Use an app to add automatic tags to Issues or PRs

### ISSUE THREAD

**Issue by eskombro** [meilisearch/integration-guides#10]
Add some **automatic tags** to newly created Issues or PRs would be very useful to organize SDK workflow. Use automation tools, filtering, etc...

[Trafico](https://github.com/marketplace/trafico-pull-request-labeler) is used by [Berty](https://github.com/berty)

There is also [Auto-labeler](https://github.com/apps/auto-labeler)

**Comment by eskombro** [comment]
It may be interesting to look for a bot that can change the status of an issue in the `SDK Project` from `doing` to `Need review` when a linked PR has a requested review

**Comment by curquiza** [comment]
To resume, here are the tasks:
- [] a bot to add the related label for each issue opened. For example, if I open an issue on the SDK ruby, the bot adds the label `SDK Ruby` to this issue.
- [] a bot to pass an issue from `Doing` to `Need Review` in the [SDK board](https://github.com/orgs/meilisearch/projects/3) when we add a reviewer to the linked PR.

@eskombro do you think you need more investigation or this issue can be started? (I don't say it should be done immediately, but just to know the state of this issue).

**Comment by eskombro** [comment]
I have been doing some research and haven't find any option for the second task. The only option might be building our own app with [probot](https://github.com/search?p=4&q=topic%3Aprobot-app&type=Repositories) but seems a little bit overkill. Maybe our approach is wrong, its true that an issue doens't need review, does it make sense to have that workflow? Maybe it makes more sense if`Need review` has the PR and not the issue.

The first task is good and I whink we all agreed on it, so I can start implementing it if everybody is ok!

**Comment by curquiza** [comment]
Ok, so, I understand that the second task (bot to pass an issue from `Doing` to `Need Review`) might be overkill. We'll discuss that in a meeting. In any case if we finally decide to implement it, another issue will be open, I think it's better to separate them.

So, the final task:
```
A bot to add the related label for each issue opened. For example, if I open an issue on the SDK ruby, the bot adds the label SDK Ruby to this issue.
```
can start, after the approval of @bidoubiwa 🙂

**Comment by bidoubiwa** [comment]
I approve this proposition: 
> a bot to add the related label for each issue opened. For example, if I open an issue on the SDK ruby, the bot adds the label SDK Ruby to this issue.

Now about the second proposition, after some reflection, I think @eskombro makes a good point. 
Maybe, `need review` should only contain PR's. Those PR's could be linked to issues from the `doing` column. That way, when we close the PR, both the PR from the `need review` column and the associated issue(s) will be closed automatically. 

Now of course the way we could automate that is that whenever a pull request is made on one of our integrations it is linked to the need review column. 
I know that this makes it possible for everyone to create a PR and have it added to this list, which is maybe a bad thing in case we grew. 
I suggest we still go for this solution until we have grown to a size where this should be reconsidered. Also, a positif aspect of doing this is that we know what is happening in the other SDK's at any time, even if no issues are linked to what is going on.

**Comment by curquiza** [comment]
I don't like the idea of duplication on the same board: the PRs are already accessible via the issues. We are going to have more and more issues, I'm afraid the dashboard becomes unreadable if we have the issues AND the PRs in the same display.
Plus it means adding label + project for each PR.

**Comment by curquiza** [comment]
I close this issue since we don't really use a workflow process with the GitHub `Projects` anymore.
I will open an accurate new one when we will decide exactly what we want for https://github.com/orgs/meilisearch/projects/3
