### ISSUE TITLE
Use `movies` instead of `books` in the documentation

### ISSUE THREAD

**Issue by mdubus** [meilisearch/integration-guides#102]
We should use examples with `movies` in every integration's readme for more consistency with the documentation of meilisearch (ex : https://github.com/meilisearch/meilisearch-js)

**Comment by bidoubiwa** [comment]
I agree with you! 

I think we should replace the small book dataset that is provided in the readme and change it with a similar small movie dataset. In order for readme's example to word with documentation examples.

**Comment by curquiza** [comment]
Do you want our getting starting to import the JSON movies dataset, or to provide a small dataset (5-6 documents) with movies instead of books?

**Comment by bidoubiwa** [comment]
I would say the second option @curquiza so that they still can copy/paste the code from the readme. But at least it would be compatible if they are following the documentation along.

**Comment by eskombro** [comment]
> I would say the second option @curquiza so that they still can copy/paste the code from the readme. But at least it would be compatible if they are following the documentation along.

+1

**Comment by bidoubiwa** [comment]
I will make an issue stating all changes that need to be done in the README's

**Comment by curquiza** [comment]
Closed in favor of #103
