### ISSUE TITLE
Remove $ signs from terminal code examples

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#103]
Following these issues #99 and #102, README.md should be updated like this

## 1. Remove $ in front of command lines

closes: #99
example: meilisearch/meilisearch-js/pull/827
As stated in de [markdownlint recommendetation](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md014), `$` should not be displayed if no output of the commands are showed. 

Example: 

Wrong ❌: no output, no `$` signs
```bash
$ ls
$ cat foo
$ less bar
```

Correct: ✅ 
```bash
ls
cat foo
less bar
```

Correct: ✅. As there are output, there should be a `$` signed to 
```bash
$ ls
foo bar
$ cat foo
Hello world
$ cat bar
baz
```
These dollar signs should be removed from the following files: 
- README.md
- CONTRIBUTING.md
- .code-samples.meilisearch.yaml
- any other markdown file in a sub directory

### Remove $

- [x]  meilisearch-dotnet
- [x]  meilisearch-go
- [x]  meilisearch-java
- [x]  meilisearch-js
- [x]  meilisearch-php
- [x]  meilisearch-python
- [x]  meilisearch-ruby
- [x]  meilisearch-rust
- [x]  meilisearch-swift
- [x] [Laravel Scout](https://github.com/meilisearch/meilisearch-laravel-scout)
- [x] [.Net](https://github.com/meilisearch/meilisearch-dotnet)
- [x] [Dart](https://github.com/meilisearch/meilisearch-dart)
- [x] [Symfony](https://github.com/meilisearch/meilisearch-symfony)
- [x] [Angular](https://github.com/meilisearch/meilisearch-angular)
- [x] [React](https://github.com/meilisearch/meilisearch-react)
- [x] [Vue](https://github.com/meilisearch/meilisearch-vue)
- [x] [VuePress plugin](https://github.com/meilisearch/vuepress-plugin-meilisearch)
- [x] [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch)
- [x] [docs-searchbar.js](https://github.com/meilisearch/docs-searchbar.js)
- [x] [meilisearch-digitalocean](https://github.com/meilisearch/meilisearch-digitalocean)
- [x] [meilisearch-aws](https://github.com/meilisearch/meilisearch-aws)
- [x] [meilisearch-kubernetes](https://github.com/meilisearch/meilisearch-kubernetes)
- [x] [Cloud Scripts](https://github.com/meilisearch/cloud-scripts)
- [x] [docs-scraper](https://github.com/meilisearch/docs-scraper)
- [x] [meilisearch-wordpress](https://github.com/meilisearch/meilisearch-wordpress)

**Comment by curquiza** [comment]
For the $ issue, I will use an automated tool 🙂 I know it might not work everywhere like in the Rust SDK repo, so thanks a lot @sanders41 for this PR (https://github.com/meilisearch/meilisearch-rust/pull/117)
