### ISSUE TITLE
Add issue template for integration repo

### ISSUE THREAD

**Issue by alallema** [meilisearch/integration-guides#116]
**Description:**
Add issue Template to guide writing and facilitate answers and readability without discouraging contributors.

**Templates considering:**
- Bug report
- Feature request
- Other or Question

**Comment by curquiza** [comment]
I let you open a PR that add this template in one repo so that we can approve your template

**Comment by alallema** [comment]
This PR will act as approval
https://github.com/meilisearch/meilisearch-python/pull/247

**Comment by curquiza** [comment]
Done!
