### ISSUE TITLE
Add method to get the raw index

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#120]
Currently, our SDKs provide a method to get an index (often named `getIndex`) but this method returns an instance of an index. Users might want to get the raw version of the index, I mean the object returned by the MeiliSearch server.

Some SDKs already provide a way to get this raw index but this is not convenient, example in PHP: `$client->index('movies')->fetchRawInfo();`

I think a `getRawIndex` method, accessible from the client, would be more convenient.

Prototype:

```
getRawIndex(string indexUID) -> object/struct/dict of the MeiliSearch response
```

Ex in python:
```python
client.get_raw_index('movies')
```

⚠️ This method should be implemented even in the SDKs that already provide a way to get the raw index, without code duplication of course!

## TODO

- [x] meilisearch-dart
- [x] meilisearch-dotnet
- [x] meilisearch-go
- [x] meilisearch-java
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [x] meilisearch-rust
- [ ] meilisearch-swift

**Comment by brunoocasali** [comment]
I'm closing this, since the popular SDKs already have this improvement :)
