### ISSUE TITLE
Add updateAt and createdAt in the index class

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#121]
When manipulating indexes (get/create/update), the SDKs return an instance of `Index` which already contains the `primaryKey` attribute.

ex:
```python
index = client.index('movies')
index.primary_key
```

But we cannot do:
```python
index.updated_at
index.created_at
```

We should be able to do this so that every information are available from the index instance.

## TODO

- [x] meilisearch-dart
- [x] meilisearch-dotnet
- [ ] meilisearch-go
- [x] meilisearch-java
- [ ] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [ ] meilisearch-rust
- [x] meilisearch-swift

**Comment by curquiza** [comment]
Addition to the Python SDK, it's already implemented in:
- Dart SDK
- Java SDK
- Swift SDK

And partially implemented in 
- JS SDK (for example, the attributes are not updated in `getRawInfo`)

**Comment by curquiza** [comment]
Addition to the Python SDK, it's already implemented in:
- Dart SDK
- Java SDK
- Swift SDK

And partially implemented in 
- JS SDK (for example, the attributes are not updated in `getRawInfo`)

**Comment by curquiza** [comment]
The issues have been open in the different repositories.

**Comment by brunoocasali** [comment]
Yes, would be awesome to get an official perspective from the core team! 

I've read about other implementations, about who is using the converted data object (not searched in every implementation):

- https://github.com/meilisearch/meilisearch-dotnet/pull/170
- https://github.com/meilisearch/meilisearch-python/pull/261
- https://github.com/meilisearch/meilisearch-dart/blob/15287f6e08b1f35faaf2b5ff221222b02d5ac306/lib/src/index.dart#L13
- https://github.com/meilisearch/meilisearch-swift/blob/518cc19652e6a921bc829ed3319841100e8f3ab8/Sources/MeiliSearch/Model/Index.swift#L28

**Comment by curquiza** [comment]
Hello @bb and @brunoocasali! Thanks a lot for your intervention here, this is really pleasant to work with contributors who care about all the SDKs 😄 

Even if we like the conformity over the SDKs (ex: provide the same kind method so that there are all convenient to use) we always want to prioritize one thing: to be idiomatic with the language. If you, as Ruby developers, think this is better to have Time object instead of String, we trust you :)

Your feedback to other languages you like/master is also more than welcome :)

**Comment by bb** [comment]
Update: the meilisearch-ruby PR was changed to use the Time class and merged.

I also stumbled over https://github.com/meilisearch/meilisearch-js/pull/1056#discussion_r728772207

**Comment by brunoocasali** [comment]
Since only one SDK is missing, and it has its issue, there is no need to keep this open!

I'll close it, thanks, team! ❤️
