### ISSUE TITLE
get_all_indexes should return a list of instance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#122]
Currently, the `get_all_indexes` method in our SDKs returns a list of dict/struct/object, but not a list of `Index` instance. This is the only index-related method that does not return `Index` instance.

An instance is more convenient to manipulate than the object/struc/dict. See this [example](https://github.com/meilisearch/meilisearch-python/issues/258#issuecomment-835866135).

I suggest:
- we change the return of the current `get_all_indexes`: make it return a list of `Index` instances
- we provide a `get_all_raw_indexes`: a method that returns the list of dict/object/struct of indexes, so the response of the MeiliSearch server.

⚠️ No code duplication: use `get_all_raw_indexes` in `get_all_indexes`.

## TODO

- [x] meilisearch-dart
- [x] meilisearch-dotnet
- [x] meilisearch-go
- [x] meilisearch-java
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [x] meilisearch-rust
- [ ] ~meilisearch-swift (not applicable)~

**Comment by brunoocasali** [comment]
Done! 🎉 🎉 🌮 🥖
