### ISSUE TITLE
Examples to run MeilISearch: replace Docker examples by `curl` examples

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#145]
Two examples to run MeiliSearch are present in our repository documentation:
- in the README, in the `Installation` section. Ex: https://github.com/meilisearch/meilisearch-ruby#-installation
- in the CONTRIBUTING, in the `Development Workflow` section. Ex: https://github.com/meilisearch/meilisearch-ruby/blob/main/CONTRIBUTING.md#development-workflow

Both of these examples launch MeiliSearch using Docker.

Some issues with this Docker command:
- This can make the users think the easiest way to launch MeiliSearch is with Docker, but it's not, it's using `curl` since `curl` is on almost every machine (more than Docker at least).
- Some user does not know the `latest` image with Docker is not pulled each time you run and think being up to date with the latest version of MeiliSearch but there are not. This leads us to add the following line in the CONTRIBUTING:
```bash
docker pull getmeili/meilisearch:latest # Fetch the latest version of MeiliSearch image from Docker Hub
```
- When trying to onboard external contributors and make them run tests locally, we sometimes end up with the contributor saying "I don't know how to use Docker" or "I don't have Docker on my machine" and we have to explain they can run tests without Docker, cf one of my comments: https://github.com/meilisearch/meilisearch-swift/pull/215#issuecomment-945723636

First, WDYT about this Docker command as the default example?
Have you encountered any problems like me?

Secondly, if you agree I can do a PR as a suggestion of change 😄 
@alallema @bidoubiwa

**Comment by bidoubiwa** [comment]
I think you are right. We should replace it with the `curl` example. Also adding a link to a tutorial on how to open a terminal so that the user has no friction at all in running MeiliSearch

**Comment by curquiza** [comment]
I opened this PR as final approval: https://github.com/meilisearch/meilisearch-js/pull/1060

**Comment by curquiza** [comment]
Implemented everywhere! 🎉
