### ISSUE TITLE
NDJSON/CSV methods to add and update documents

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#146]
Following: https://github.com/meilisearch/integration-guides/issues/142

MeiliSearch v0.23.0 introduces two changes:
- new valid formats to push data files, additionally to the JSON format: CSV and NDJSON formats.
- it enforces the `Content-type` header for every route requiring a payload (`POST` and `PUT` routes)

Here are the expected changes in every SDK (some of them are already implemented in PHP and Python SDKs when I'm writing this issue)

- [ ] Currently, the SDKs always send `Content-Type: application/json` to every request. Only the `POST` and `PUT` requests should send the `Content-Type: application/json` and not the `DELETE` and `GET` ones.

- [ ] Add the following methods and 🔥 **the associated tests** 🔥 to ADD the documents. Depending on the format type (`csv` or `ndjson`) the SDK should send `Content-Type: application/x-dnjson` or `Content-Type: text/csv`)
  - [ ] `add_documents_json(string docs, string primary_key)`
  - [ ] `add_documents_csv(string docs, string primary_key)`
  - [ ] `add_documents_csv_in_batches(string docs, int batch_size, string primary_key)`
  - [ ] `add_documents_ndjson(string docs, string primary_key)`
  - [ ] `add_documents_ndjson_in_batches(string docs, int batch_size, string primary_key)`

- [ ] Add the following methods and 🔥 **the associated tests** 🔥 to UPDATE the documents. Depending on the format type (`csv` or `ndjson`) the SDK should send `Content-Type: application/x-dnjson` or `Content-Type: text/csv`)
  - [ ] `update_documents_json(string docs, string primary_key)`
  - [ ] `update_documents_csv(string docs, string primary_key)`
  - [ ] `update_documents_csv_in_batches(string docs, int batch_size, string primary_key)`
  - [ ] `update_documents_ndjson(string docs, string primary_key)`
  - [ ] `update_documents_ndjson_in_batches(string docs, int batch_size, string primary_key)`

`docs` are the documents sent as `String`
`primary_key` is [the primary key of the index](https://docs.meilisearch.com/learn/core_concepts/indexes.html#primary-key)
`batch_size` is the size of the batch. Example: you can send 2000 documents in raw String in `docs` and ask for a `batch_size` of 1000, so your documents will be sent to MeiliSearch in two batches.

Example of PRs:
- in PHP SDK: https://github.com/meilisearch/meilisearch-php/pull/235
- in Python SDK: https://github.com/meilisearch/meilisearch-python/pull/329

----------

TODO in:
- [ ] meilisearch-dart
- [ ] meilisearch-dotnet
- [ ] meilisearch-go
- [ ] meilisearch-java
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [ ] meilisearch-rust
- [ ] meilisearch-swift

**Comment by brunoocasali** [comment]
Since the issues were open in the SDKs, I think we can safely close this one :)
