### ISSUE TITLE
SDK individual documentation

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#15]
### State 
As of today, the documentation of the SDK's only exists in their respective readme. 
Following stripe's way, the [SDKs](https://stripe.com/docs/libraries) do not have independent documentation except for the front-end javascript sdk. 

- [Strapi API references](https://stripe.com/docs/api)
- [Strapi  JS SDK](https://stripe.com/docs/js)

Potentially, we want to add more complex functions to all the SDK's and at that point we might consider independent documentation for the SDK's.

### Commentary Documentation

Meanwhile! My suggestion is to use the commentary-documentation of each language
python example: 
<img width="532" alt="Screenshot 2020-05-04 at 22 54 07" src="https://user-images.githubusercontent.com/33010418/81012634-2f4d0900-8e5a-11ea-9de6-4523e01a0879.png">

In each popular language there (should) exist libraries that let you build a documentation based on those comments ([pdoc3](https://pdoc3.github.io/pdoc/) for python). Maybe we could consider creating `language.meilisearch`.com with the generated documentation. 

For example it would be `python.meilisearch.com` for the doc generated py pdoc3. 

Those commentary-documentation are also useful for IDE as they use those commentaries to generate tooltips.

Example with `writeFileSync`

function + comments: 
<img width="989" alt="Screenshot 2020-05-04 at 23 42 36" src="https://user-images.githubusercontent.com/33010418/81016656-26ac0100-8e61-11ea-99a9-a2e449478505.png">

Generated tooltip when using this function in another project: 

<img width="652" alt="Screenshot 2020-05-04 at 23 46 43" src="https://user-images.githubusercontent.com/33010418/81016869-8b675b80-8e61-11ea-9812-87a24e2e7f53.png">

### Pros: 
- Tooltip when using the SDK in external projects
- Generated documentation

### Cons: 
- It takes time to cover every function

_(note: it is already done in python SDK minus potentially review, and halfway done in javascript SDK)_

### Conclusion:

Three suggestion of which I would like to discuss, know your opinion, and get your possible approval

- We create commentary for every wrapper function following the best practice of each language (and the libraries that exists see JSdoc for js, [pdoc](https://pdoc3.github.io/pdoc/) for python, [phpDoc](https://fr.wikipedia.org/wiki/PHPDoc) for php etc etc.. ). 
- We generate the documentation with the appropriate library that _should_ exists (pydoc3 for Python, [phpDocumentator](https://www.phpdoc.org/) for PHP, jsdoc for js, etc ..)
- We create a language.meilisearch.com with the results of that documention

**Comment by curquiza** [comment]
After discussing, we think it's a huge work and it will involve a lot of duplication with the API reference documentation (if we do it, cf #3)
But it seems necessary for the tooltip and for the methods which are not in API References (like `deleteAllIndexes` or `waitForPendingUpdate`).

It should be implemented in the future. At least preparing the comment, and open an issue as `good_first_issue` so that contributors can complete them.

**Comment by brunoocasali** [comment]
Closed in favor of the new tracking issue for this subject #201.
