### ISSUE TITLE
Fix `get-latest-meilisearch-rc.sh` script

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#154]
The current [`get-latest-meilisearch-rc.sh` script](https://github.com/meilisearch/integration-guides/blob/main/scripts/get-latest-meilisearch-rc.sh) is currently wrong in some tricky cases. The purpose of this script is to get the latest RC (so pre-release) and return its "name", for example `v0.23.0rc1`.

### How does the script work currently?

It gets all the MeiliSearch releases (the releases but also the pre-releases), and take the first one at the of the list, assuming the one at the top is the last one in terms of date. Which is wrong, it's the last one it terms of GitHub release ID.
Ex: I release `v0.23.0rc0` on Tuesday, but on Wednesday I release `v0.23.0rc1` using a release draft that was created one month ago -> the release at the top of the list will be `v0.23.0rc0` and not `v0.23.0rc1`. This happened by mistake to us, without knowing the consequence of taking an "old" draft for create a new release.

### Solution

I don't know any good solution at the moment. A good way would be the availability to request the latest pre-release to the GH API, but I did not find any way in the API at the moment.
Waiting for a solution to be suggested 😇 In the meantime, the current script is the less worst solution.

**Comment by brunoocasali** [comment]
@curquiza I'm closing this. I'm not aware of any problems coming from this subject in a while. Let me know if I'm mistaken!
