### ISSUE TITLE
code-samples: Add `sortableAttributes` missing

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#155]
Following the documentation issues (https://github.com/meilisearch/documentation/issues/1290) and PR (https://github.com/meilisearch/documentation/pull/1291) we should add the code sample related to `sortableAttributes`.

**code-sample-id**: `search_parameter_guide_sort_1`

**code-sample example in curl**:
```bash
curl \
  -X POST 'http://localhost:7700/indexes/books/settings' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "sortableAttributes": [
      "price",
      "author"
    ]
  }'
```

FYI, the dotnet SDK does not have its code-samples up to date.

**Comment by curquiza** [comment]
Close this! Implemented everywhere! Well done @bidoubiwa and @alallema!!
