### ISSUE TITLE
`attributesToRetrieve` param works only as string type in `getDocument`

### ISSUE THREAD

**Issue by alallema** [meilisearch/integration-guides#167]
**Describe**
Now, it is possible to send the `attributeToretreive` parameter either as a `string` or as an `array` with the search method.
This is not the case with the `getDocument` method.
Because the parameter is sent via the `URL` and can't be sent as an `array`.

This issue is opened following this [contributor issue](https://github.com/meilisearch/meilisearch-php/issues/288).

**To Reproduce**
PHP:
```php
$hits = $client->index('movies')->getDocuments(['limit' => 2, 'offset' => '2', 'attributesToRetrieve' => ['title','poster']]);
print_r($hits);
```
```
PHP Fatal error:  Uncaught MeiliSearch ApiException: Http Status: 400 - Message: Query deserialize error: unknown field `attributesToRetrieve[0]`, expected one of `offset`, `limit`, `attributesToRetrieve` - Code: bad_request - Type: invalid_request - Link: https://docs.meilisearch.com/errors#bad_request
  thrown in /Users/amelielallemand/Projects/meili/repo/meilisearch-php/src/Http/Client.php on line 215
```
Python:
```python
print(client.index('movies').get_documents({'limit':2, 'attributesToRetrieve': ['title', 'poster']}))
```
```json
[{}, {}]
```
**Normal behavior:**
PHP:
```php
$hits = $client->index('movies')->getDocuments(['limit' => 2, 'offset' => '2', 'attributesToRetrieve' => 'title, poster']);
```
```php
Array
(
    [0] => Array
        (
            [title] => Master Z: Ip Man Legacy
        )

    [1] => Array
        (
            [title] => Ralph Breaks the Internet
        )

)
```
Python:
```python
print(client.index('movies').get_documents({'limit':2, 'attributesToRetrieve': 'title, poster'}))
```
```json
[{'title': 'Guardians of the Galaxy'}, {'title': 'Fantastic Beasts: The Crimes of Grindelwald'}]
```

**Question**:
Should we allow this behavior on all SDK or warn the user that this parameter is only used in `string` for this method?

**Comment by sanders41** [comment]
Thinking of the Python client, because you know exactly what is allowed my suggestion would be to change the method signature to take the specific parameters rather than a random dictionary. This way the user of the library knows exactly what to send and as the maintainer of the library you know exactly what you will get.

```py
def get_documents(
        self, *, offset: int = 0, limit: int = 20, attributes_to_retrieve: Optional[str] = None
    ) -> Optional[list[dict[str, Any]]]:
    ...
```

**Comment by alallema** [comment]
Hi @sanders41,
I'm totally agreed, I think we should do it on every SDK as well if it's not the case. I didn't check for all of it

**Comment by sanders41** [comment]
@alallema if you do move forward with this it may be worth considering it for the other methods that do the same thing. For example the index `create` method also takes a dictionary `options` as a parameter, but the only valid value in `options` would be the primary key.

**Comment by alallema** [comment]
@sanders41 Indeed but I was wondering more about this one because this parameter `attributeToretreive` can be sent in two ways to the API and I think it can be a bit confusing for the user if he uses it in both places.
Maybe we should add some code samples

**Comment by bidoubiwa** [comment]
Meilisearch-js uses the `GET /search` route so it changes the `["title", "description"]` into `"title,description` [see this code](https://github.com/meilisearch/meilisearch-js/blob/main/src/lib/indexes.ts#L115). 

It is up to us to know if we want to provide that ease of use to the user. I think it is better that we provide that.

**Comment by alallema** [comment]
Yes @bidoubiwa, you did everything resume! This is the question.

**Comment by bidoubiwa** [comment]
Since we are providing a tool and not an http library I think it is something we should do. The user should have the most intuitive experience. Asking to join an array is creating unexpected complexity

**Comment by brunoocasali** [comment]
_disclaimer: taking the risk to say something useless here, but trying to get up on the train!_

So, the idea is to support only arrays in the public method API and internally make the transformation to string like the js integration or support both ways?

If I understood correctly, I definitely agree with the idea to **receive the parameter as an array** and deal internally + **remove the support of passing the string only** (thinking in other implementations that could be difficult to know when the user wants to split the string or not).

**Comment by sanders41** [comment]
@brunoocasali I might be right there with you of saying something useless here 😄 ...in Python you could take either a string or array from the user and handle it for them.

```py
def get_documents(
        self, *, offset: int = 0, limit: int = 20, attributes_to_retrieve: Optional[Union[str, List]] = None
    ) -> Optional[list[dict[str, Any]]]:
    if isinstance(attributes_to_retrieve, list):
        formatted_attributes = ','.join(attributes_to_retrieve)
    else:
        formatted_attributes = attributes_to_retrieve

    ...
```

Taking only an array would certainly also be possible. What I don't know is do people ever send a single attribute to retrieve? If not it doesn't seem to make sense to support both. Also in certain languages, like Rust, this either/or option wouldn't work.

**Comment by bidoubiwa** [comment]
Since it is considered an array type by the meilisearch engine, and described as such by the documentation, I think we should only support arrays. 
In the case of query parameters the array may look like a string when there is only one element but I think we should not have to add compatibility with strings because of that special behaviour. 

What do you think?

**Comment by sanders41** [comment]
Taking only an array and formatting it for the user makes sense to me, and may be what @alallema was thinking all along and I just missed it.

**Comment by brunoocasali** [comment]
This may not be relevant anymore since every SDK supports arrays. Let me know if this is a mistake.
