### ISSUE TITLE
Rebranding changes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#168]
Because of the meilisearch’s [new rebranding](https://www.meilisearch.com/) 🎉  we need to apply some changes to our repositories
- Change the logo on every README if needed
- Change the naming of `MeiliSearch` into `meilisearch`. Do not apply any changes regarding the codebase, I mean, do not change `MeiliSearchClient` into `MeilisearchClient` since it will break the API of the SDK. Every breaking changes for the users should NOT be done now. We will discuss later in another issue.

TODO

- [x] meilisearch-dotnet https://github.com/meilisearch/meilisearch-dotnet/pull/227
- [x] meilisearch-dart https://github.com/meilisearch/meilisearch-dart/pull/134
- [x] meilisearch-go https://github.com/meilisearch/meilisearch-go/pull/259
- [x] meilisearch-java https://github.com/meilisearch/meilisearch-java/pull/323
- [x] meilisearch-js https://github.com/meilisearch/meilisearch-js/pull/1143
- [x] meilisearch-php https://github.com/meilisearch/meilisearch-php/pull/290
- [x] meilisearch-python https://github.com/meilisearch/meilisearch-python/pull/403
- [x] meilisearch-ruby https://github.com/meilisearch/meilisearch-ruby/pull/294
- [x] meilisearch-rust https://github.com/meilisearch/meilisearch-rust/pull/224
- [x] meilisearch-swift https://github.com/meilisearch/meilisearch-swift/pull/250
- [x] meilisearch-rails https://github.com/meilisearch/meilisearch-rails/pull/105
- [x] meilisearch-symfony https://github.com/meilisearch/meilisearch-symfony/pull/157
- [x] meilisearch-angular https://github.com/meilisearch/meilisearch-angular/pull/8
- [x] meilisearch-react https://github.com/meilisearch/meilisearch-react/pull/24
- [x] meilisearch-vue https://github.com/meilisearch/meilisearch-vue/pull/98
- [x] instant-meilisearch https://github.com/meilisearch/instant-meilisearch/pull/656
- [x] docs-searchbar.js https://github.com/meilisearch/docs-searchbar.js/pull/533
- [x] firestore-meilisearch https://github.com/meilisearch/firestore-meilisearch/pull/31
- [x] gatsby-meilisearch https://github.com/meilisearch/gatsby-plugin-meilisearch/pull/109
- [x] strapi-plugin-meilisearch https://github.com/meilisearch/strapi-plugin-meilisearch/pull/342
- [x] vuepress-plugin-meilisearch https://github.com/meilisearch/vuepress-plugin-meilisearch/pull/206
- [x] meilisearch-digitalocean https://github.com/meilisearch/meilisearch-digitalocean/pull/251
- [x] meilisearch-aws https://github.com/meilisearch/meilisearch-aws/pull/61
- [x] meilisearch-gcp https://github.com/meilisearch/meilisearch-gcp/pull/42
- [x] meilisearch-kubernetes https://github.com/meilisearch/meilisearch-kubernetes/pull/99
- [x] cloud-scripts https://github.com/meilisearch/cloud-scripts/pull/71
- [x] js-project-boilerplate https://github.com/meilisearch/js-project-boilerplate/pull/4
- [x] meilisearch-migration https://github.com/meilisearch/meilisearch-migration/pull/15
- [x] integration-guides https://github.com/meilisearch/integration-guides/pull/170
- [x] integration-automation

**Comment by alallema** [comment]
Be careful I think the `aws` logo has change [see](https://github.com/meilisearch/meilisearch-aws/issues/24)

**Comment by curquiza** [comment]
Not an issue, it's normal since this PR changed the logos ;)
https://github.com/meilisearch/integration-guides/pull/169

**Comment by curquiza** [comment]
I forgot to link the second PRs to this central issue sorry 😢

**Comment by brunoocasali** [comment]
@curquiza should we add a label to these PR's?

**Comment by brunoocasali** [comment]
I think it need to be `skip-changelog` like this https://github.com/meilisearch/meilisearch-symfony/pull/157#event-5964196175

**Comment by curquiza** [comment]
I also forgot to add automatically the `skip-changelog` label to every PR, the second run of PR was really bad, sorry 😓

**Comment by curquiza** [comment]
This is dooooooooooone!!!!!
Congrats @brunoocasali @alallema and @bidoubiwa for your reactiviy!

**Comment by brunoocasali** [comment]
I've added skip-changelog to all PR's who haven’t that yet :)
