### ISSUE TITLE
Update READMEs with new release process step

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#17]
Related to my answer in the [Release Discussion](https://github.com/meilisearch/discuss/discussions/24#discussioncomment-9090).

Since we have contributors doing great and useful work, I want to add a new step to our Release Process.
This process is described in each README in the `Workflow Development` -> `Release` section.

So far we have (for the Ruby one, the others are almost the same except for PHP and Laravel):

```md
MeiliSearch tools follow the Semantic Versioning Convention.

You must do a PR modifying the file lib/meilisearch/version.rb with the right version.

VERSION = 'X.X.X'

Once the changes are merged on master, in your terminal, you must be on the master branch and push a new tag with the right version:

$ git checkout master
$ git pull origin master
$ git tag vX.X.X
$ git push --tag origin master

A GitHub Action will be triggered and push the new gem on RubyGems.
```

I want to add this sentence right after this paragraph and in the same section:

```md
Then, you must create a release for this tag via the [GitHub interface](https://github.com/meilisearch/meilisearch-ruby/releases) (by editing the tag).<br>
The release description should detail:
- the changes merged since the last release with the link to the related PRs.
- the names of external contributors who participated in this release.
```

For the Laravel and PHP SDKs, I will only add the second part of this paragraph, because the release process already asks for creating a release via the GitHub interface.

Steps:
- Go -> There is no `Release` process in the Go README yet
- [ ] JS
- [ ] Laravel
- [ ] PHP
- [ ] Python
- [ ] Ruby
- Swift -> Does not have any `Workflow Development` at all yet

**Comment by eskombro** [comment]
So is it required to create the `lib/meilisearch/version.xx` file in every SDK? Meaning a standard place to check for the current version? Because, as for now, that is not the case in several packages (such as Python or Go)

Also, do we need to have an extension like .rb or .go for a version file? Cant we use a standard txt file or something (like no extension, and just a `0.10.1` as content?

**Comment by curquiza** [comment]
There is a misunderstanding with the ruby example because a ruby package needs this kind of file. But it does not mean we need to have a `version` file for each SDK. Take a look at each SDK release process section, you will see the exact file(s) you need to change 😉

For the Go, it's more complicated because I indeed don't know how the versioning works for go.

**Comment by eskombro** [comment]
Approved!

**Comment by curquiza** [comment]
I thought about another way to process. I will take the time to detail that soon, but for now, I removed the `ready to implement` label in case you finally will choose my new suggestion 😊

**Comment by curquiza** [comment]
I close this in favor of #33 that describes the new release process and the release-drafter workflow.
