### ISSUE TITLE
Meilisearch and Svelte

### ISSUE THREAD

**Issue by umgefahren** [meilisearch/integration-guides#178]
Hi, I would like to ask if there are any plans to provide a Svelte integration.
This would be very cool, because Svelte is a really promising framework and more fun to use then the alternatives.

**Comment by brunoocasali** [comment]
By the way @umgefahren you could vote for this integration here: https://roadmap.meilisearch.com/tabs/1-under-consideration

**Comment by brunoocasali** [comment]
I'll close this since we don't have any plans to work on new integrations right now! This may change in the future. Let us know if you think that's a mistake!

Check it out https://github.com/meilisearch/meilisearch-js-plugins. It should work for svelte :)
