### ISSUE TITLE
Changes regarding Meilisearch v0.26.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#181]
This issue gathers the changes related to the v0.26.0 of Meilisearch that will impact the integrations.

**Release date: 14/03/2022**

The whole milestones of v0.26.0 here: https://github.com/meilisearch/meilisearch/milestones/27

----

## New flag behavior

Related to https://github.com/meilisearch/meilisearch/issues/2097

It means every `--no-analytics=true` are now `--no-analytics`

This impacts every integration in our
- CIs
- examples in CONTRIBUTING.md
- some docker-compose files if they exist

⚠️ We will try to automate most part of the work with octopus (internal tool), but please, check no `--analytics=true` has been forgotten.

## New dump behavior

Related to
- this issue https://github.com/meilisearch/meilisearch/issues/2087
- this spec: https://github.com/meilisearch/specifications/pull/105

Some changes impact [meilisearch-migration](https://github.com/meilisearch/meilisearch-migration/).

Two changes in v0.26.0:
- When importing a dump using `--import-dump` if a database already exists, an error message will be thrown on the CLI.
- Similar to the behavior of the snapshot feature. The flags `--ignore-dump-if-db-exists` and `--ignore-missing-dump` are added. -> does not impact meilisearch-migration if I'm correct.

## Tenant tokens

Related to:
- this issue: https://github.com/meilisearch/meilisearch/issues/1991
- this spec: https://github.com/meilisearch/specifications/pull/89

We have to add a `generateToken` method to every SDK following the spec requirement to make it easy to generate the token for the future search of the user.

Some instruction
- for the JS SDK -> only implementing for Node.js, not for front-end.
- As first, try not to use any other library, but if it's not possible, use the most appropriate one.
- Maybe this will need discussion to find the most user-friendly way to provide the method. Should stay doable regarding the deadline (4 weeks during the pre-release).

🔥 We should add tests 🔥

-----

TODO:
The PR linked below should be merged

**Comment by brunoocasali** [comment]
@brunoocasali, @bidoubiwa, and @alallema decided in an internal meeting:

Regarding the `token generation`, we should have a method like this:

```c#
client.generateTenantToken(Object searchRules, DateTime expiresAt:?, String apiKey:?) => String
```
ps: `expiresAt` and `apiKey` are named/keyword params.

If the language doesn't support named parameters it should use:
```c#
client.generateTenantToken(Object searchRules, Object options?) => String
```

The implementation of the token generation should be done without a library but having one is not "prohibited".
When the `apiKey` is not present we will use the current `apiKey` from the `MeiliSearchClient` instance called the `generateTenantToken` method.

**Comment by brunoocasali** [comment]
Follow up about validations:

Since we will not be able to cover all the aspects regarding the validations we still need to add some checks in the `generateTenantToken` implementation:

- `expiresAt`: should be in the future, should be in `UTC`, should be a `date`/`time` object, could be `null`.
- `searchRules`: should be a `string`, `array` or `hash`, `hashmap`, `object`, should not be a `null` value.
- `apiKey`: should be a `string`, could be `null`.

**Comment by alallema** [comment]
> * `searchRules`: should be a `string`, `array` or `hash`, `hashmap`, `object`, should not be a `null` value.
I don't think `searchRules` could be a `string` no?

**Comment by bidoubiwa** [comment]
> searchRules: should be a array or hash, hashmap, object, should not be a null value.

Iike @alallema said. While it is true that it should not be a null, it also should not an integer or boolean etc.. 
Maybe we should removed the `should not be a null` and only check if `searchRules` is the following 
> array or hash, hashmap, object

**Comment by alallema** [comment]
> Iike @alallema said. While it is true that it should not be a null, it also should not an integer or boolean etc..
> Maybe we should removed the should not be a null and only check if searchRules is the following

I agree with @bidoubiwa, I think it would be nice to test the type but depending on the language we can always check if the `searchRules` are not null in case.

**Comment by brunoocasali** [comment]
@alallema @bidoubiwa updated!

**Comment by brunoocasali** [comment]
Congratulations @meilisearch/integration-team we made it! 🎉 🎉 

🎶 🎵 🎶 🎵 WE ARE THE CHAMPIONS!! 🎶 🎵 🎶 🎵
