### ISSUE TITLE
Add Blazor support in the instant-meilisearch

### ISSUE THREAD

**Issue by ahmetkocadogan** [meilisearch/integration-guides#183]
First of all, thank you for this amazing search tool.

My question is, is Blazor going to be supported like meilisearch-blazor ?

Thank you.

**Comment by ahmetkocadogan** [comment]
@curquiza  thank you :)

**Comment by brunoocasali** [comment]
Hi @ahmetkocadogan unfortunately, we do not have the resources to work on your suggestion yet!

You can check our current roadmap here: https://github.com/meilisearch/integration-guides/blob/main/roadmap/2022.md
And if you want to make an official suggestion add it here: https://roadmap.meilisearch.com

But can you make my mind clearer regarding this? I only know Blazor from the news and didn't check that yet. Currently, we maintain the [.NET SDK](https://github.com/meilisearch/meilisearch-dotnet) to integrate the .net apps with Meilisearch in the server. So are you proposing an instant-meilisearch version for Blazor?

**Comment by ahmetkocadogan** [comment]
Hi @brunoocasali 

Thanks for fast response.

Yes, what i'm asking is instant-meilisearch version for Blazor, like this https://github.com/meilisearch/meilisearch-angular

**Comment by brunoocasali** [comment]
@ahmetkocadogan thanks!

Can you help me understand more how we could make that conversion? Microsoft or the community has some guides regarding this kind of situation? I need to understand if this "conversion" is something feasible from our side or not. 
And could you give me some numbers regarding the possible market share, the community size, etc. of this new integration?

Btw, we have some integrations that are maintained by the community https://github.com/meilisearch/awesome-meilisearch/#community-integrations if you want you could start it, and we can help you along the way!

**Comment by ahmetkocadogan** [comment]
@brunoocasali hello.

Blazor website is here : https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor

Blazor lets .NET developers use C# instead of javascript. What i like about it, it makes web development easier and more accessible to .NET developers. I personally never liked to work with javascript, but thanks to Blazor, now i don't have to, at least most of the time.

By asking Blazor support for instant search, what i am asking is, is it in your plans or can be in your plans to add Blazor version of instant-search.

I don't know how to give you the numbers, market share, community size etc. but i guess we can look at the repo it lives and issue counts.

I'll take a deeper look into meilisearch instant-search repo's and try to evaluate that if it is possible or worth it or not. Maybe i can start to code it and hopefully make it work.

**Comment by maxibyte** [comment]
First of all, thank you for your hard work. We know that the meilisearch-team is certainly still very busy, but is there any news regarding this? I think many Blazor/C# developers would love to see meilisearch-blazor. Blazor and Meili are both great tools that we would like to combine to build great web apps. 
Thank you.

**Comment by brunoocasali** [comment]
Hi @maxibyte, how are you?

Unfortunately is improbable the @meilisearch/integration-team will work on this integration in the following quarters. We are now focusing on other stacks we would like to partner with. Blazor is also in our plans but only far away in the future due to our internal team size.

I would like to encourage you or anyone else to work on this integration personally, and we will be happy to help across the path :) 

Thanks a lot for using Meilisearch! 🚀

**Comment by brunoocasali** [comment]
I'm cleaning this repo, and unfortunately, my last message is still relevant, we're a small team and don't have much time to work on new and shiny integrations. I would love to see the community stepping in and making an integration for this!

I'll close this issue :)
