### ISSUE TITLE
Remove support for node 12 and add support for node 18

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#196]
Javascript SDK's currently run their tests on the following node versions: 
- Node 12 
- Node 14
- Node 16

Since the 30 Apr 2022 node [12 is end of life](https://endoflife.date/nodejs). Thus we do not have to maintain support for this versions.

From now on we should test the following versions: 

- Node 14: Maintenance mode until the 30 Apr 2023
- Node 16: Active support
- Node 18: Current version

<img width="766" alt="Screenshot 2022-05-05 at 13 23 23" src="https://user-images.githubusercontent.com/33010418/166913518-2a55a5c4-9134-4b40-ac95-c9ef4ea7c2fd.png">

- These changes must be made in all yaml files used for the CI. 
- In the compatibilities declared in the README

**Comment by brunoocasali** [comment]
Since the issues were created in each repository, I will close this. We can track this issue there.
