### ISSUE TITLE
Jekyll plugin

### ISSUE THREAD

**Issue by tristone13th** [meilisearch/integration-guides#200]
Many people are using Jekyll to host their blogs and websites, can we implement a plugin for Jekyll like this: Gatsby Plugin #83 to better integrate meilisearch to Jekyll?

**Comment by brunoocasali** [comment]
Hello @tristone13th how are you?

Thanks for your message, it could be a good idea to have this integration. Can you give more information about what you expect from this plugin? And if possible show some examples of plugins, that definitely could be helpful to us!

**Comment by brunoocasali** [comment]
I'll close this since we don't have any plans to work on new integrations right now! This may change in the future. Let us know if you think that's a mistake!
