### ISSUE TITLE
SDKs hosted documentations

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/integration-guides#201]
Following a lot of [conversations](https://github.com/meilisearch/integration-guides/issues/27) and [efforts](https://github.com/meilisearch/integration-guides/issues/15) in the integrations team to implement documentation in our SDKs, the idea of this issue is to be the central issue tracking of the work.

To start the project, we will include only a few SDKs so the community can get involved in the decision and implementation, and it should be easier to handle. More SDKs can be included in the following months.

The chosen SDKs are:

- [ ]  JavaScript
- [x] [PHP](https://meilisearch.github.io/meilisearch-php/)
- [x] [Python](https://meilisearch.github.io/meilisearch-python/)
- [x] [Rust](https://docs.rs/meilisearch-sdk/latest/meilisearch_sdk/)
- [x] [Dart](https://pub.dev/documentation/meilisearch/latest/)

Each SDK will have its issues tracking the progress, which are:

- Decision regarding which module will be used
- Implement the module with a couple of requirements
    - Needs to generate the doc automatically through the CI
    - Needs to generate the docs from the comments in the source code
    - Needs to be well known by the community of that package.
    - Needs to be published automatically in a remote environment or the package manager like [meilisearch-rust](https://docs.rs/meilisearch-sdk/latest/meilisearch_sdk/).
- PS: No need to actually add the documentation after the setup, this will be done incrementally afterward.

**Comment by bidoubiwa** [comment]
One option was to keep the documentation on the same README, like javascript now. Is this still a possibility or do we prefer going for the external documentation trial first?

**Comment by brunoocasali** [comment]
But this option does not address this requirement `Needs to generate the docs from the comments in the source code` correct? Or there is a library that could generate a docs automatically?

**Comment by brunoocasali** [comment]
Just one update on this topic, we already have some of our SDKs that have this documentation already hosted automatically.

[Rust](https://docs.rs/meilisearch-sdk/latest/meilisearch_sdk/) and [Dart](https://pub.dev/documentation/meilisearch/latest/)

**Comment by brunoocasali** [comment]
It is not in our plans to add new documentations in the SDKs right now, so I'll close this :)
