### ISSUE TITLE
Code samples updates

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/integration-guides#204]
These are the samples we must update in the integrations:

Code samples Ids with **`bold`** were impacted by multiple PR's, be careful.

Code sample ID | PR | Summary
-- | -- | --
`primary_field_guide_update_primary_key` | https://github.com/meilisearch/documentation/pull/1544 | Add new code sample
`primary_field_guide_add_document_primary_key` | https://github.com/meilisearch/documentation/pull/1544 | 1. Rename code sample. Previous name: `document_guide_add_document_primary_key` <br/> 2. Update code sample
`primary_field_guide_create_index_primary_key` | https://github.com/meilisearch/documentation/pull/1544 | 1. Rename code sample. Previous name: `document_guide_create_index_primary_key` <br/> 2. Update code sample
**` ❌ updating_guide_check_version`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization header
**` ❌ updating_guide_get_displayed_attributes_new`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 https://github.com/meilisearch/documentation/pull/1651 | Add new code sample <br/> Update code sample to add authorization header Rename `updating_guide_get_displayed_attributes` to `updating_guide_get_displayed_attributes_new`
**` ❌ updating_guide_reset_displayed_attributes_new`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 https://github.com/meilisearch/documentation/pull/1651 | Add new code sample <br/> Update code sample to add authorization header Rename `updating_guide_reset_displayed_attributes` to `updating_guide_reset_displayed_attributes_new`
**` ❌ updating_guide_create_dump`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization header
**` ❌ updating_guide_get_dump_status`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization header
**` ❌ updating_guide_get_settings`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization header
**` ❌ updating_guide_retrieve_documents`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization header
**` ❌ updating_guide_update_settings`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization header
**` ❌ updating_guide_add_documents`** | https://github.com/meilisearch/documentation/pull/1598 https://github.com/meilisearch/documentation/pull/1644 | Add new code sample <br/> Update code sample to add authorization head
`primary_field_guide_update_document_primary_key` |  https://github.com/meilisearch/documentation/pull/1624 | Rename code sample. Previous name: `primary_field_guide_update_primary_key`
`getting_started_check_task_status` | https://github.com/meilisearch/documentation/pull/1568 | Rename code sample. Previous name: `getting_started_check_task_status_md`
`getting_started_update_ranking_rules` |  https://github.com/meilisearch/documentation/pull/1568 | Change code sample to use snake_case. Previous name: `getting_started_update_rankingRules`
`getting_started_update_displayed_attributes` | https://github.com/meilisearch/documentation/pull/1568 | Change code sample to use snake_case. Previous name: `getting_started_update_displayedAttributes`
`getting_started_update_searchable_attributes` | https://github.com/meilisearch/documentation/pull/1568 | Change code sample to use snake_case. Previous name: `getting_started_update_searchableAttributes`
`getting_started_geo_radius` | https://github.com/meilisearch/documentation/pull/1568 | Change code sample to use snake_case. Previous name: `getting_started_geoRadius`
`getting_started_geo_point` | https://github.com/meilisearch/documentation/pull/1568 | Change code sample to use snake_case. Previous name: `getting_started_geoPoint`
`getting_started_limit_md` | https://github.com/meilisearch/documentation/pull/1568 | Remove code sample
`getting_started_add_meteors_md` |  https://github.com/meilisearch/documentation/pull/1568 | Remove code sample
`❌  updating_guide_get_displayed_attributes_old` |  https://github.com/meilisearch/documentation/pull/1651 | Add new code sample
`❌  updating_guide_reset_displayed_attributes_old` | https://github.com/meilisearch/documentation/pull/1651 | Add new code sample

**Comment by bidoubiwa** [comment]
I updated the original message with ❌  on the code-samples that are on hold until @dichotommy comes back to us

**Comment by brunoocasali** [comment]
Again, thank you @meilisearch/integration-team for the hard and AWESOME work here!

You're the best! ❤️
