### ISSUE TITLE
Code sample changes

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/integration-guides#209]
- We will add code samples to this issue every time we merge a **non-release PR** with the `code sample changes needed` label
- If a code sample was changed both by a release PR and also by a non-release-related PR, include it in the release issue

~1. Replace `updating_guide_check_version`  [PR](https://github.com/meilisearch/documentation/pull/1650)~

~Replace with two new code samples:~
~- `updating_guide_check_version_new_authorization_header`~
~- `updating_guide_check_version_old_authorization_header`~
check: https://github.com/meilisearch/integration-guides/issues/209#issuecomment-1201377890

2. Update `getting_started_communicating_with_a_protected_instance ` [PR](https://github.com/meilisearch/documentation/pull/1720)

Replace `127.0.0.1` with `localhost`

3. Update `updating_guide_check_version_new_authorization_header ` [PR](https://github.com/meilisearch/documentation/pull/1720)

Replace `127.0.0.1` with `localhost`

4. Update `updating_guide_check_version_old_authorization_header ` [PR](https://github.com/meilisearch/documentation/pull/1720)

Replace `127.0.0.1` with `localhost`

5. Update `add_movies_json_1 ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

6. Update `getting_started_add_documents_md ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

7. Update `getting_started_search_md ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

7. Update `getting_started_add_meteorites ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

8. Update `authorization_header_1 ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

9. Update `security_guide_search_key_1 ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

10. Update `tenant_token_guide_search_no_sdk_1 ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

11. Update `updating_guide_get_displayed_attributes_new ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

12. Update `updating_guide_get_displayed_attributes_old ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

13. Update `updating_guide_reset_displayed_attributes_new ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

14. Update `updating_guide_reset_displayed_attributes_old ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

15. Update `updating_guide_create_dump ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

16. Update `updating_guide_get_dump_status ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

17. Update `updating_guide_get_settings_old ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

18. Update `updating_guide_retrieve_documents_old ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

19. Update `updating_guide_update_settings_old ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

20. Update `updating_guide_add_documents_old ` [PR](https://github.com/meilisearch/documentation/pull/1655)

Replace `127.0.0.1` with `localhost`

21. New code sample `getting_started_typo_tolerance` [PR](https://github.com/meilisearch/documentation/pull/1683)

Updates `movies` index to set: `"minWordSizeForTypos": { "oneTypo": 4 }`

**Comment by brunoocasali** [comment]
@meilisearch/integration-team let's wait a bit until start this work, I'll try to automate some of the changes, I let you know in any case :)

**Comment by brunoocasali** [comment]
Hi @meilisearch/docs-team, I have a question about the code sample number 1:

https://github.com/meilisearch/documentation/pull/1650/files#r933818730

**Comment by brunoocasali** [comment]
After the answer here https://github.com/meilisearch/documentation/pull/1650/files#r933818730, we can remove the number 1 :)

**Comment by brunoocasali** [comment]
Closing this, since all the linked PRs are merged :) 

Thanks, team! 🎉
