### ISSUE TITLE
Code sample changes

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/integration-guides#216]
1. Add `getting_started_faceting` meilisearch/documentation#1833
  Set `maxValuesPerFacet` to 2
2. Add `getting_started_pagination` meilisearch/documentation#1833
  Set `maxTotalHits` to 500
3. Add `synonyms_guide_1` meilisearch/documentation#1841
  Set `great` and `fantastic` as synonyms
4. Add `date_guide_index_1` meilisearch/documentation#1917
  add documents to index
5. Add `date_guide_filterable_attributes_1` meilisearch/documentation#1917
   - `"indexUid": "games"`
   - `release_timestamp` to `filterableAttributes`
6. Add `date_guide_filter_1` meilisearch/documentation#1917
   - `"indexUid": "games"`
   - `"q": ""`
   - `"filter": "release_timestamp >= 1514761200 AND release_timestamp < 1672527600"`
7. Add `date_guide_sortable_attributes_1` meilisearch/documentation#1917
   - `"indexUid": "games"`
   - `release_timestamp` to `sortableAttributes`
8. Add `date_guide_sort_1` meilisearch/documentation#1917
   - `"indexUid": "games"`
   - `"q": ""`
   - `"sort": ["release_timestamp:desc"]`
  
### TODO:

- [x] Generate the automated PRs

**Comment by brunoocasali** [comment]
@maryamsulemani97 can I implement the changes here, or do you want to make any changes? (maybe some last-time changes in the docs that are not up to date here?)

**Comment by maryamsulemani97** [comment]
Hi @brunoocasali,  no changes further changes were made for these code samples

**Comment by brunoocasali** [comment]
It was already done :)
