### ISSUE TITLE
Add dependabot to update CI dependencies

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#217]
Sorry if it has already been opened or discussed before

You can add a section to Dependabot file [this way](https://github.com/meilisearch/meilisearch/blob/main/.github/dependabot.yml) to avoid updating dependencies manually/with our script in your GH actions [like this](https://github.com/meilisearch/meilisearch-ruby/pull/373).
You will get [this kind of PR](https://github.com/meilisearch/meilisearch/pull/2566).

I really recommend to put `interval: "monthly"` 😇

**Comment by brunoocasali** [comment]
Thanks a lot, @curquiza I didn't know that!

I'll create those PRs automatically :)

**Comment by alallema** [comment]
I think this issue is finish 😉

**Comment by brunoocasali** [comment]
Yes, it is @alallema thanks for reminding me!

Closing this, thanks team 🎉  :)
