### ISSUE TITLE
Versioning and section "Compatibility with MeiliSearch"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#22]
For the moment, MeiliSearch is not stable and uses a version tag like `v0.X.Y`.
Currently, the SDKs are not stable either and they use the same `X` than MeiliSearch for the versioning.
Problem: the MeiliSearch breakings are not the same as the SDKs ones.

Solution: after discussion, we decided to stop following the MeiliSearch versioning. Each SDK README contains a "Compatibility with MeiliSearch" section, so we should improve this section to explain the compatibilities to the user.

Here is the sentence I suggest, for the SDK python for example, once the `v0.11` of MeiliSearch is out (the python package can stay in `v0.10.1`):

```
This package is compatible with these versions of MeiliSearch:
- `v0.11.X`
- `v0.10.X`
```

(The package might be compatible with the v0.9, but we are not going to mention the version of MeiliSearch before the `v0.10` in this section since it was before we decided to change the versioning)

### What about the previous SDK versions?

I suggest being simply because the SDKs are not stable yet. I mean do not mention the other SDK versions than the current one.
Ex: the SDK is in `v0.11`, the README will only mention the `v0.11` (which is the current SDK version) and the MeiliSearch compatibilities. We are not going to talk about previous **SDK versions** like the `v0.10` or the `v0.9` in the README of the `v0.11`.

**Comment by curquiza** [comment]
Here a PR example with the PHP SDK
https://github.com/meilisearch/meilisearch-php/pull/33

**Comment by eskombro** [comment]
> Here a PR example with the PHP SDK
> [meilisearch/meilisearch-php#33](https://github.com/meilisearch/meilisearch-php/pull/33)

Instead of writting in the SDK readme (as in the example PR):
```
This package is compatible with these versions of MeiliSearch:
- `v0.10.X`
```

I would specifically mention the current version (and former versions) as we don't know at what moment MeiliSearch core could introduce a change that breaks an SDK. So I would propose something like:

```
This package is compatible with these versions of MeiliSearch:
- `v0.10.1` or lower
```

**Comment by curquiza** [comment]
> But I know this would imply more work for every new MeiliSearch release. So what's your opinion on that?

Not sure I'm really motivated to change all the READMEs for each release of MeiliSearch 😬
Since we don't have a bot to do that, I suggest we use my first suggestion 🙂

**Comment by bidoubiwa** [comment]
I agree with your suggestion @curquiza but don't you think this should be mentioned sooner in the readme and with more flavor text?

## Suggestion

## 🤖 Compatibility with MeiliSearch

This package heavily depends on the [version of MeiliSearch](https://docs.meilisearch.com/references/version.html) you are using. Every version of [this package](https://github.com/meilisearch/meilisearch-php/releases) is compatible up to a certain version of MeiliSearch. If you upgrade MeiliSearch, pay attention to the compatibility with this package. If the package version does not support your MeiliSearch version, it should be upgraded.

This package works for MeiliSearch `>=v0.10`.
This package is compatible with these versions of MeiliSearch:
- `v0.10.X`

**Comment by curquiza** [comment]
I like having an explication text before. What do you think @tpayet and @eskombro about the text? Could you improve it or it is clear and ok for you?

> This package works for MeiliSearch >=v0.10.
This package is compatible with these versions of MeiliSearch:

    v0.10.X

Why twice?

**Comment by bidoubiwa** [comment]
Bad copy paste from your PR sorry

**Comment by tpayet** [comment]
The @bidoubiwa explanation lost me. I know @bidoubiwa is really into linking everything together but I do not agree on this one. I do not feel we need that much text to explain compatibility..
It would be clearer with @curquiza original suggestion imho, let's keep it simple for now!

**Comment by bidoubiwa** [comment]
Alright! And about putting @curquiza suggestion higher in the readme?

**Comment by tpayet** [comment]
Yes! 👍 it should be before development workflow and after the getting started. But I do not know where compared to the examples

**Comment by curquiza** [comment]
I put it right after the getting started. Is it "too soon"? (Reminder: there is alway a TOC in READMEs)

https://github.com/meilisearch/meilisearch-php/blob/d6c82fe5688bec9e1ee538eff3ec9a7e5a4c08fa/README.md

**Comment by eskombro** [comment]
> I've just changed to put it right after the getting started. Is it "too soon"? (Reminder: there is alway a TOC in READMEs)
> 
> https://github.com/meilisearch/meilisearch-php/blob/d6c82fe5688bec9e1ee538eff3ec9a7e5a4c08fa/README.md
> 
> (Spoiler: the Dev workflow will probably put in a CONTRIBUTING.md file in the future)

This seems perfect to me, simple, clear and in the right place.

I would change the text for:

```
This package is compatible with the following versions of MeiliSearch:
```

**Comment by curquiza** [comment]
All READMEs have been updated.
