### ISSUE TITLE
Sending a new primary key when it already exists, should it be blocking?

### ISSUE THREAD

**Issue by eskombro** [meilisearch/integration-guides#23]
While I was [working in the Python SDK](https://github.com/meilisearch/meilisearch-python/issues/84) I realized that you can send a primary key as a aparameter while creating or updating documents. If a primaryKey is already set, the default behavior seems to be the same [in MeiliSearch](https://docs.meilisearch.com/references/documents.html#add-or-replace-documents) and in every SDK:  it ignores your 'new' primary key, and makes the addition/modification you requested. No exception or error, no notification, nothing, it is just ignored.

In my opinion, this leads the user to think that the 'new' primary key was set, and lead to confusion and introducing bugs in different parts of his code (as it "seems" to work) without understanding what happened exactly and it might be hard to debug afterwards.

I propose throwing an error/exception/panic to tell the user he's actually requesting something that can't be done!

Python current index.update_documents() method:

```python
def update_documents(self, documents, primary_key=None):
        """Update documents in the index

        Parameters
        ----------
        documents: list
            List of dics containing each a document, or json string
        primary_key: string
            The primary-key used in MeiliSearch index. Ignored if already set up.
        Returns
        ----------
        update: `dict`
            Dictionnary containing an update id to track the action:
            https://docs.meilisearch.com/references/updates.html#get-an-update-status
        """
        if primary_key is None:
            url = '{}/{}/{}'.format(
                self.config.paths.index,
                self.uid,
                self.config.paths.document
            )
        else:
            url = '{}/{}/{}?{}'.format(
                self.config.paths.index,
                self.uid,
                self.config.paths.document,
                urllib.parse.urlencode({'primaryKey': primary_key})
            )
        return self.http.put(url, documents)
```

I would appreciate your opinion on this!

**Comment by eskombro** [comment]
This may be a COre discussion (or at least before discussing anything for the SDKs).
I created an issue here: https://github.com/meilisearch/MeiliSearch/issues/738

**Comment by curquiza** [comment]
Closing this since it's a core discussion.
A more general discussion could be open about warnings in the SDKs
