### ISSUE TITLE
How should we use code-samples to generate a list of the features implemented in the different SDK's

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#244]
Recently, we added a code-samples report to ensure we are up to date with the required samples.
You can find that [list here](https://docs.meilisearch.com/sample-report/).

Using this list, we can also infer what feature is implemented in which SDK or not.
For example:

<img width="1343" alt="Screenshot 2023-02-15 at 12 23 28" src="https://user-images.githubusercontent.com/33010418/219014261-be2bcd55-eec7-4bb3-aed2-e1d673fe8870.png">

## Issue

Nonetheless, there are some issues going in that direction.

- There are a lot of redundant code-samples showcasing the same features. For example `getting_started_synonyms`, `synonyms_guide_1` and `update_synonyms_1`
- Some code-samples are using work-around hiding the fact that the feature is not implemented. For example in settings code-sample may use the `global` setting route and not the subroutes. In which case we do not know if these subroutes have been implemented.
- There are code-samples that are not clear in what they showcase: `date_guide_sort_1`
- While the standard routes have code-samples (ex: get_documents), some query/body parameters do not have dedicated code-samples (ex: get_documents_with_primary_key). Which results in us not knowing if that query parameter is added in the SDK. For example, adding `pagination` in the settings structure of a typed language.

## Solution ?

Not a lot of possible solutions that would cover all the issues mentioned above.
The only one I can think of is:
- We start adding our own code samples that the docs might use if they want to 🤷‍♀️
- We find a better naming convention to intuitively understand what the code-sample showcases. Example: `date_guide_sort_1`, with`search_sort_by_date_1` (just an example). From which we can regex the `search_` samples. Of course better naming may be found.
- We find a way to tag the code-samples that are relevant to us in the [sample template file](https://github.com/meilisearch/documentation/blob/main/.vuepress/public/sample-template.yaml) that contains the list of all existing templates.

## Conclusion

It's harder than we initially thought. I'm not very creative in my solutions and I don't think the final result will be satisfying.

What do you think?

**Comment by brunoocasali** [comment]
This is an excellent idea, and we should put some effort into this topic once and for all. 
But the issue is that we will have fewer and fewer code-samples on the SDKs. Only a few SDKs will receive updates, so I think this could be safely closed until we have more definition about what we should do with them.
