### ISSUE TITLE
Add `canceled` status to Task statuses in all SDK's README

### ISSUE THREAD

**Issue by alallema** [meilisearch/integration-guides#245]
**Description**
Currently, the different statuses are listed in the readme after an example.
In v0.30 the `canceled` status was added to the API return Task statuses but was not updated in the readme:

With the `uid`, you can check the status (`enqueued`, `processing`, `succeeded` or `failed`) of your documents addition using the [task](https://docs.meilisearch.com/reference/api/tasks.html#get-task).

It should be updated.

**Comment by brunoocasali** [comment]
Raising a question: 
Is it valid to duplicate the role of the documentation in this kind of code? If we only keep the link, we don't need to worry about it again...

In any case I agree with the change @alallema.

**Comment by bidoubiwa** [comment]
Maybe we could change this: 

> Tasks such as document addition always return a unique identifier. You can use this identifier taskUid to check the status (enqueued, processing, succeeded or failed) of a [task](https://docs.meilisearch.com/reference/api/tasks.html#get-task).

To this:

```
Tasks such as document addition always return a unique identifier. You can use this identifier `taskUid` to check the status of a [task](https://docs.meilisearch.com/reference/api/tasks.html#get-task).
```

So that we avoid having to maintain that sort of documentation in the readme's. 

What do you think?

**Comment by alallema** [comment]
> So that we avoid having to maintain that sort of documentation in the readme's.

Yes I agree it's also good not to put all the possible status, but maybe we should add something like

```
Tasks such as document addition always return a unique identifier. You can use this identifier `taskUid` to check the status of a [task](https://docs.meilisearch.com/reference/api/tasks.html#get-task) and see if it has been processed.
```

To be sure the user know that the task is asynchrone.

**Comment by brunoocasali** [comment]
Done!
