### ISSUE TITLE
Replace docs.meilisearch.com with meilisearch.com/docs in every repository.

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/integration-guides#257]
Since the docs have a new domain, we must update the current occurrences from our repositories.

Search by occurrences in

- `CONTRIBUTING.md`
- `README.md`
- `code-samples.meilisearch.yml`

-----
- [x] automate the work

**Comment by curquiza** [comment]
Notification rain incoming ☔ 🌈

**Comment by bidoubiwa** [comment]
All PR's have been opened in all integrations repositories. I should have mentioned this issue in their PR body. My bad :/

**Comment by ahmednfwela** [comment]
this link appears to be broken https://www.meilisearch.com/docs/learn/what_is_meilisearch/contact, is there a replacement for it ?

**Comment by bidoubiwa** [comment]
Yes! @alallema found it: https://discord.com/invite/meilisearch

**Comment by brunoocasali** [comment]
Time to a new automation!

**Comment by brunoocasali** [comment]
Done! 🏁
