### ISSUE TITLE
Examples section in README

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#26]
Currently, all the SDKs have an `Examples` section.

Maybe I'm in the future because it's not done yet for all the SDK but anyway 😬... once an SDK has completed all the examples for the main docs (I mean docs.meilisearch.com) including examples in guides ([like the JS does](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#example-5)), not only in the API references, I think we should remove the `Example section` and redirect the user to the API references.

What do you think?

(I don't forget that some custom methods for SDKs like `wait_for_pending_update` are not going to be documented in the main docs, but the current `Example` section is not related to them and I suggest we discuss that in another discussion 😉)

If you agree with this removal, how could we redirect **clearly** to the API references?

**Comment by eskombro** [comment]
I am not sure about that. Docs examples are a must have, but they are examples of every single functionality / route, their nature is not the same. They are short, simple, straightforward. But they don't have the same value as an example of a 'hello world' working project creating a client, an index, adding documents, etc. The readme examples show you the 'workflow' for which you need way more time and mental effort to get from the docs directly. It is great to have a copy/paste working example that let you play directly with a new product/project without needing to read the docs and understand the main concepts. When you have this, you try it, you see it works, then you get curious and read the docs. Well, that's my point of view, but I don't really understand why you want to remove it. I mean, you are proposing it but I don't see clearly what the argument is. 

About the custom methods, I was actually thinking about it yesterday and I'll make a different discussion as you suggest

**Comment by curquiza** [comment]
Sorry, I wasn't clear because it was obvious to me, but it's not.

When you write a README you have 2 possibilities:
- write the docs on the README
- redirect to the official docs

We didn't have any docs for the SDKs, that's why we use the `Examples` section.

But most of the famous packages do not use README for docs, they redirect the user to the official one in the first paragraphs:
- Algolia: https://github.com/algolia/algoliasearch-client-ruby 
- Stripe (all the example are specific to the SDKs and does not correspond to the [API methods you can find in their docs](https://stripe.com/docs/api)): https://github.com/stripe/stripe-ruby

I took both of them because they offer good documentation experience, but you can find the same behavior for other packages, like [Sidekiq](https://github.com/mperham/sidekiq) or [Scrapy](https://github.com/scrapy/scrapy)... When the package is coming bigger and bigger, the solution is often to give up the README documentation and focus on an official and clearer one.

Plus, my suggestion avoids duplication of documentation.

For me, redirect the user to the official docs could be a good practice. It's not mandatory, but it's a solution we should consider, especially because we are not stable and maintain double documentation could be a pain.
That's why I suggest that 😉

What do you think @tpayet and @bidoubiwa?

**Comment by eskombro** [comment]
After reading your explanation I totally agree with you. My bad, I did think you were also thinking about getting rid of the `getting started` section. If that section stays on the readme, I don't think we need to keep / maintenant the `examples` section, and we can delete it, indeed 👍

**Comment by curquiza** [comment]
That's my fault, I should have written that at first 😅 I posted it too fast! 😇

**Comment by curquiza** [comment]
@bidoubiwa @eskombro : I didn't get any answer about

> If you agree with this removal, how could we redirect clearly to the API references?

It could be simple, but I want your opinion on:
- what kind of sentence
- where in the README
- ...

**Comment by eskombro** [comment]
I think we should replace the `Examples` section (in place) with a short invitation to read the docs as follows (my first proposition to start with):

<hr>

## 🎬 Documentation and examples

MeiliSearch documentation provides **examples** and a detailed explanation of every one of it's features and functionalities, including examples on how to implement them **using this SDK**. 

Please read our [Documentation guides](https://docs.meilisearch.com/guides/) or check the [API References](https://docs.meilisearch.com/references/) to find the one that you need!

**Comment by eskombro** [comment]
@bidoubiwa 🚀 ? :)

**Comment by curquiza** [comment]
I pass it as `ready to implement` 😉

**Comment by curquiza** [comment]
I was thinking about implementing this issue since some of our packages have the code-samples, but I want to suggest an imporvement:

<hr>

## 🎬 Documentation and Examples

MeiliSearch documentation provides **examples** and a detailed explanation of every one of its features and functionalities, including examples on how to implement them **using this SDK**. 

Please read our [documentation guides](https://docs.meilisearch.com/guides/) or check the [API References](https://docs.meilisearch.com/references/) to find the one that you need!

The following sections may interest you:

- [Manipulate documents](https://docs.meilisearch.com/references/documents.html)
- [Search](https://docs.meilisearch.com/references/search.html)
- [Manage the indexes](https://docs.meilisearch.com/references/indexes.html)
- [Configure the index settings](https://docs.meilisearch.com/references/settings.html)

<hr>

I would like to add the "basic" section of the API references, because, when clicking on the [API References](https://docs.meilisearch.com/references/) link, we don't see any example even when scrolling on the page. This can be confusing, that's why I suggest to add the most useful sections that contains examples 🙂

What do you think @bidoubiwa @eskombro?

**Comment by eskombro** [comment]
I agree, it is more explicit, yet quite short and helpful! 🚀

**Comment by bidoubiwa** [comment]
Hey ! Seems nice :) 

What do you mean by "basic" section of the API references ?

And also, i would change "documentation guides" with either `guides` or `guides available in the documentation`
When I read `documentation guides` i feel like the guides are about documentation in general.

**Comment by curquiza** [comment]
Edited!

Basic sections are the most needed sections in API references when you use MeiliSearch -> Index + Documents + Search + Settings (not Keys or Updates or Stats or Health)

**Comment by curquiza** [comment]
To make the approval easier (via commits suggestion), I open a PR that will be the reference for this issue 🙂
https://github.com/meilisearch/meilisearch-python/pull/150

**Comment by curquiza** [comment]
What we really want for the a SDK's README when removing the example section is finally defined in this PR: https://github.com/meilisearch/meilisearch-go/pull/85

To add more information about this decision, I re-investigate what the other similar opensource projects are doing for their docs on the README.

Most of the open source API client with external docs do not re-write in the README all the API-related methods present in these external docs (often the API references). There are basic usages and getting started sections, but not a summary of all the methods available related to the API routes. If the README is long, it’s because of the amount of SDK-related usages and methods.

See:
- [GitHub API client](https://github.com/PyGithub/PyGithub)
- [Gitlab API client](https://github.com/NARKOZ/gitlab): there are quick usages examples but more focused on the SDK than the API-related methods. They only show to fetch a user and a project. 
- [Algolia API Client](https://github.com/algolia/algoliasearch-client-javascript)
- [Stripe API Client](https://github.com/stripe/stripe-js)
- [Twilio client](https://github.com/twilio/twilio-ruby/)

The only opposite example I found is the the [Digital Ocean API clients in Ruby](https://github.com/digitalocean/droplet_kit) that keeps all the examples in the README, despite the [external docs](https://developers.digitalocean.com/documentation/v2/).
We have choosen to do like the majority for the moment but it could be really inspiring if we decide to come back with API-methods in the README.

I close this issue until someone think this is necessary to re-open the debate 😁
