### ISSUE TITLE
Add references to the user-agent in the guide about creating a new integration

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/integration-guides#262]
We do have a guide about how to create a new meili integration https://github.com/meilisearch/integration-guides/blob/main/resources/build-integration.md

And we now have a nice and clean way to understand the behavior of our users as you can see here: https://github.com/meilisearch/integration-guides/issues/150

Based on that, it would be nice to see third-party integrations in the usage graphs!

**Comment by bidoubiwa** [comment]
Definitely a good idea :)

**Comment by brunoocasali** [comment]
Done https://github.com/meilisearch/integration-guides/commit/7468c7c0ce805114f3182ec38a5a7f4aff184811
