### ISSUE TITLE
Write some guidelines about meilisearch integrations into external repositories

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/integration-guides#269]
I just learned that we had a connection with Airbyte. And in fact, I just heard about it because it is broken.

So, I suggest keeping a paper trail of Meilisearch presence into other tools that may be relevant or not in our internal processes, ex: In the past, we had to deal with some breaking changes on the Laravel Scout side. We did that because Laravel Scout is an important integration for us, but we do not directly maintain it. 

So the idea is to keep a list in the integration-guides where we can track all those open-source packages. Plus by doing it we may warn them about new features it could be implemented for example.

The current list of external integrations are:

- [Airbyte](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/destination-meilisearch)
- [Medusa.js](https://github.com/medusajs/medusa/tree/develop/packages/medusa-plugin-meilisearch)
- [Laravel Scout](https://github.com/laravel/scout/blob/10.x/src/Engines/MeilisearchEngine.php) 

My question for the @meilisearch/integration-team is, is it worth having such tracking? Or we could just have a section in the awesome-meilisearch and that would be ok?

**Comment by brunoocasali** [comment]
My only concern is to invest time in inactive integrations or abandoned ones. Otherwise, I'm ok with that. It is still our brand in the game. But of course, some situations are not worth it, spend time on it, and that's also good!

Because if we take the Airbyte one, for example. By keeping a working version of our plugin inside Airbyte, we can guarantee users can adopt Meilisearch even easier from whatever data source they may have.

What bugs me is that I, the integrations manager, didn't know its existence!

**Comment by sanders41** [comment]
@brunoocasali this is admittedly not the best process, but what I have done is use the used by page (https://github.com/meilisearch/meilisearch-python/network/dependents for example) to find people using my packages and then I will occasionally check  their issues for anything I can help with. 

I suspect that with the GitHub API there would be a way for you to gather the used by information so you have some visibility into it in an aggregated way. It's not 100% of the users but maybe a start.

**Comment by brunoocasali** [comment]
That's an excellent idea indeed! Even if they show at least the more relevant packages would be helpful!

**Comment by brunoocasali** [comment]
Unfortunately, we don't have time to create a new process like this one, even if it is helpful. 

If someone from the community spots any issue in an integration like this, please reach us in the discord so we can help!
