### ISSUE TITLE
Add cloud touch points on SDKs/Integrations repos README

### ISSUE THREAD

**Issue by gmourier** [meilisearch/integration-guides#277]
Following https://github.com/meilisearch/mini-dashboard/issues/441 initiative, we could insert  touch points for the cloud in every SDKs/Integrations README files to raise awareness.

- We could add a section before/after the "Contributing" section so it's not invasive
    - That section could be fueled with the same message and link of #441
    - We can set the `&utm_source=` query parameter per SDKs/Integration in the link
- Add a "Meilisearch Cloud" link to the top banner; (same link as the one contained in the dedicated section)

e.g

### Section Example

![Capture d’écran 2023-06-14 à 22 14 13](https://github.com/meilisearch/integration-guides/assets/3692335/5d705f2a-8fb1-47ea-b2aa-9a0f4a3214e4)

![Capture d’écran 2023-06-14 à 22 13 22](https://github.com/meilisearch/integration-guides/assets/3692335/8701d559-fbba-4cc7-bf35-12d45e6371cf)

### Top Header Example

![Capture d’écran 2023-06-14 à 22 15 32](https://github.com/meilisearch/integration-guides/assets/3692335/6e1bacb2-3e35-49e9-b4bf-8e59cb0ac227)

cc @mayasssh, @davelarkan

**Comment by brunoocasali** [comment]
@gmourier Besides some manual changes, most of our repositories have the link now. 🪖

**Comment by brunoocasali** [comment]
@meilisearch/integration-team please check every repo in your scope and merge it accordingly.

**Comment by brunoocasali** [comment]
Done, all the integration repositories have this communication now :)

**Comment by brunoocasali** [comment]
New step: add the
