### ISSUE TITLE
Change the usage of the search method

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#28]
Following this issue: meilisearch/MeiliSearch#729 the `placeholder` search is soon to arrive in MeiliSearch. The placeholder search is meant to have search results even on request without any search query.

> The displayed documents are sorted by the custom criteria specified in the settings when the query parameter is empty or not present at all (i.e /search?q= or /search).

This implies that the `query` query parameter will not be mandatory anymore. 

I think it is confirmed by what I observe in the source code:
```
fn new_search(&self, query: Option<String>) -> SearchBuilder;
```
Where `Option` makes it optional.

Should we reconsider the usage of the search method in most of our clients
from: 
```javascript
search(query: string, parameters: object)
```
to:
```javascript
search(parameters: object)
```

**Comment by curquiza** [comment]
I approve!

I would add the `parameters` parameter in the `search` method should optional (when it's possible in the language)

**Comment by eskombro** [comment]
Does this mean that `query` becomes an optional parameter inside the `parameters` object?

**Comment by curquiza** [comment]
Almost: `q` becomes an optional parameter inside the `parameters` object.

**Comment by bidoubiwa** [comment]
After discussing it, 

- We keep the prototype like it is
- Still, tests should be added to ensure that this is possible: `search('')`
- Should we transform any `search(null)` into an empty string or should we let MeiliSearch tell the user that `none` is not a valid input?

**Comment by curquiza** [comment]
> Should we transform any search(null) into an empty string or should we let MeiliSearch tell the user that none is not a valid input?

For a better user experience, I would say `none` = `q=""` or even no `q` at all in the request body

**Comment by curquiza** [comment]
Closing this issue!
