### ISSUE TITLE
Update cloud link

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#281]
According to requested changes, see the [internal slack message](https://meilisearch.slack.com/archives/C010VV3SHQF/p1690383323193389?thread_ts=1690383144.175919&cid=C010VV3SHQF)

> 1. We should now link to https://www.meilisearch.com/cloud instead of the pricing page
> 2. Replace `utm_source=integration` with `utm_source=github` to follow the latest [UTM tracking conventions](https://www.notion.so/meilisearch/64b3356d2ce84d87b4fe22feb91f4d82?v=1612b9eee2e34352ab55ea64f45074ba).

**Comment by brunoocasali** [comment]
Done @curquiza :)
