### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#33]
It's been a long time I'm thinking about adding a CONTRIBUTING.md file, especially when I saw @erlend-sh was starting [the PR for the MeiliSearch repository](https://github.com/meilisearch/MeiliSearch/pull/749).

The goal of this file is to:
- Explain the different step to contribute
- Add Development Workflow (and remove the current one from the README 🎉)
- Give guidelines about the git workflow and our expectation
 
Of course, I took most of my inspiration in the Erlend's PR but I tried to take into account the Kero remark: not to provide a too long file that could discourage some contributors. The `Development Worklow` needs to be detailed and accurate of course since it's mandatory to work. But I tried to make the `Git Guidelines` simple (and that's why I put it to the end of the file). As we are beginners in the OS community, I would rather a contributor who contributes but we need to redirect him/her to the CONTRIBUTING.md, that no contribution at all.

⚠️ It could be great if **all the team could follow all of these guidelines from now**, since we are examples for the next contributors 🙂 Don't panic, all the rules are really basics and I did not add any new rules you are not already aware about it. It's just that, sometimes, you know, we forget to apply them 🙃

The goal here is to make it simple with no complexe rules, but to give a base and a reference to our contributors. Thus, and since the rules are really easy to follow, if you notice a contributor that does not follow the guidelines, don't hesitate to redirect him to the CONTRIBUTING.md file (nicely of course 😇).

<s>**As it's not convenient at all to discuss together about a CONTRIBUTING.md template here, I'm going to create a PR that everyone is welcome to review 😉**</s> the PR #34 is merged now.

# Edit

Here is the [final contributing template](https://github.com/meilisearch/integration-guides/blob/master/templates/CONTRIBUTING.md).

In every repository READMEs, we need to:
- add it in every repo
- remove the `Development Workflow` section in the README and replace it by this section https://github.com/meilisearch/integration-guides/issues/33#issuecomment-652972504

Todo:
- [x] meilisearch-dotnet
- [x] meilisearch-go
- [x] meilisearch-js
- [x] meilisearch-laravel-scout
- [x] meilisearch-php
- [x] meilisearch-python
- [X] meilisearch-ruby
- [x] meilisearch-swift
- [x] meilisearch-symfony
- [x] vuepress-plugin-meilisearch
- [x] docs-searchbar.js
- [x] docs-scraper

**Comment by curquiza** [comment]
Now, in each repo, let's:
- add a CONTRIBUTING.md file according to the new [templates](https://github.com/meilisearch/integration-guides/blob/master/templates/CONTRIBUTING.md)
- remove the `Development Workflow` section in the README

I'm updating the issue description with the repositories list.

**Comment by eskombro** [comment]
We shoul replace the '⚙️ Development Workflow' section in every readme to something like:

<hr>

## ⚙️ Development Workflow and Contributing

Any new contribution is more than welcome in this project!

If you want to know more about the development workflow or want to contribute, please visit our [contributing guidelines](CONTRIBUTING.md) for detailed instructions!

<hr>

**Comment by curquiza** [comment]
All the SDKs have a CONTRIBUTING.md now, closing then!
