### ISSUE TITLE
POST Search in MS v0.13.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#37]
According to this PR, MeiliSearch is going to have a `POST /indexes/:uid/search` route. The `GET` is still there of course

How should we handle it in our SDKs?

I checked and Algolia only uses the `POST` one in their SDKs for the `search` method:
- [Ruby](https://github.com/algolia/algoliasearch-client-ruby/blob/cd0cb358adfdbc0ecc403eba74f51c9ee5fa9c47/lib/algolia/index.rb#L161)
- [PHP](https://github.com/algolia/algoliasearch-client-php/blob/ce8b35a5aa842ad3e0dc05bbd7aaf5ed82481d71/src/SearchIndex.php#L52)
- [Python](https://github.com/algolia/algoliasearch-client-python/blob/a2802d6eb283f6477d2faa9911c9d0ac8f63530a/algoliasearch/search_index.py#L312)
- ...

Two options:

1. Do the same as Algolia. The `GET` method for search should only be used in specific cases so MS needs to keep it but is way slower. See [this discussion](https://github.com/meilisearch/discuss/discussions/47). Even Algolia [warns us to us it](https://www.algolia.com/doc/rest-api/search/#search-index-get).
As the `GET` method is used in really specific cases and might lead to performance issues, considering not to use it **until a user asks for it** could be an option.

2. Rename the `search` method into `search_with_get` and the new `search` method would use `POST`. However, it means duplicating the code and most of all, all the tests. It could be a little bit painful for nothing...

I have a preference for option 1: it involves less work until our users ask for it 🙂

What do you think @tpayet, @eskombro, @bidoubiwa?

NB: of course, the prototype for the `search` method will not change because of the `POST` usage, and will be as described in #28.

## Implementation

- [x] [meilisearch-go](https://github.com/meilisearch/meilisearch-go/issues/64)
- [x] [meilisearch-js](https://github.com/meilisearch/meilisearch-js/issues/505)
- [x] [meilisearch-dotnet](https://github.com/meilisearch/meilisearch-dotnet/issues/34)
- [x] [meilisearch-swift](https://github.com/meilisearch/meilisearch-swift/issues/26)
- [x] [meilisearch-php](https://github.com/meilisearch/meilisearch-php/issues/66)
- [x] [meilisearch-python](https://github.com/meilisearch/meilisearch-python/issues/126)
- [x] [meilisearch-ruby](https://github.com/meilisearch/meilisearch-ruby/issues/71)

**Comment by bidoubiwa** [comment]
Mmmh.
The code for the `post` search must be done. In either cases. Neither the tests or the implementations exists and is too different from the `get` search.

The existing code for the `get` search works and its respective tests also works. 

In which case the difference between option 1 and 2.

Option 1: 
1. Code the search with post.
2. Make the tests for the search with post
3. Remove the tests and the old get search implementations

Option 2:
1. Code the search with post.
2. Make the tests for the search with post
3. Rename the old `search` to `get_search` (or whatever we decide)

The main work would potentially be during maintenance I guess. 

I was going to say I prefered option 1. But after thinking about the changes needed I think option 2 and option 1 are the same amount of work.

**Comment by curquiza** [comment]
The tests are already done, we are not changing the behavior of the method. So option 1 does not need to change anything in the tests suite.

**Comment by bidoubiwa** [comment]
Well the post method works a little differently than the get method. For example, `facetFilters` is not a string but a real array in the post method.

I feel like the work to make option 2 is anecdotique. 
- Copy pasting the tests and changing the name
- Changing the actual `search` to `get_search` (or whatever the name)
- Creating the `post` search

Option 1 does not require the first bullet point. Which does not seem like a lot of work. Maybe I'm missing something.

**Comment by curquiza** [comment]
>  Well the post method works a little differently than the get method. For example, facetFilters is not a string but a real array in the post method.

For me it's not that hard to change. We had to adapt the code to pass it as a string... we can finally remove this part.

> Maybe I'm missing something.

You forgot the maintenance, it means maintaining two functions with duplicated tests... Or we can create a function tool in our tests that runs both each time (for post and get), but it means creating this function = for each SDK, understanding how the tests framework works to create this tool. For one SDK it's ok, but for 8, that's significative work...
Same, maintaining duplicated tests for one SDK is ok, for 8 it's not the same...

**Comment by tpayet** [comment]
We will have to maintain both methods unfortunately. At first we thought we would deprecate the GET search, but it is a feature that is still needed. 

The GET search is not advised only when it comes to front-end integration because of CORS and pre-flight request. IMHO, we should go for solution 2, but keep in mind that the search route are of little use in back-end sdk but must be heavily tested on the JS sdk 😬

**Comment by curquiza** [comment]
Ok, 2 people against 1, except if @eskombro strongly wants the option 1 (in this case let's discuss it in meeting maybe?) we will go with the option 2 🙂
@eskombro?

**Comment by eskombro** [comment]
I am sorry to ask this but... why would the SDKs need to use the get route if we migrate everything to POST? Why can't we deprecate it (not for MS but for the SDKS)

**Comment by curquiza** [comment]
Don't be sorry 😄 I let @tpayet or @bidoubiwa answering since I'm the one wanting the option 1 😇

**Comment by eskombro** [comment]
I do prefer option 1, since I am actually not able to see a use-case that would 'need' to use GET over POST. And maintaining both doesn't make sense unless there is actually a use-case for it

**Comment by bidoubiwa** [comment]
From the discuss about deprecating `GET` https://github.com/meilisearch/discuss/discussions/47#discussioncomment-20870
> The problem is that sites with many data and many searches with very different search configurations, notably App search in SaaS/B2C or e-commerce, can't use cache at all.
On the other hand, sites that use search for their website/documentation etc. Generally, don't use any search configuration; every configuration can be done on the backend side. In this case, it would be quite possible to hide the results of queries with a cache provider.
A cache provider cannot cache a POST query.
This means it would still require two routes to search and, therefore, duplicate code.
Why not, imagine in the future, if the need arises. A search request with a GET that can only receive the query parameter and have the client use this route automatically if there are no other options passed by the user.

**Comment by eskombro** [comment]
So if someone uses a cache system in between the SDK and the MeiliSearch instance this would be an issue? In this case I'm afraid we are going to have to maintain both options.

**Comment by curquiza** [comment]
Final decision:

Only the JS SDK will implement both functions with this prototype:
```js
search(query, options={}, method='post')
```

**Comment by curquiza** [comment]
Finally closing this issue!
