### ISSUE TITLE
Settings changes in MS v0.13.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#39]
Related to this issue https://github.com/meilisearch/MeiliSearch/issues/824, the settings are going to change in the v0.13.0.

For the SDKs, it means:
- updating the tests accordingly to the new behaviors
- remove the `acceptNewFields` routes

TODO:
- [x] meilisearch-go
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [x] [meilisearch-swift](https://github.com/meilisearch/meilisearch-swift/issues/48)

**Comment by ppamorim** [comment]
We are still working on the essential fixes in the unit and integration tests, this will be one of the next things to work on.

**Comment by curquiza** [comment]
Finally closing this issue!!
