### ISSUE TITLE
Bump MeiliSearch v0.14.0

### ISSUE THREAD

**Issue by eskombro** [meilisearch/integration-guides#41]
Create Bump MeiliSearch v0.14.0 branch and test with v0.14.0 release candidate

- [x] [Python](https://github.com/meilisearch/meilisearch-python/pull/146)
- [x] [Go](https://github.com/meilisearch/meilisearch-go/pull/76)
- [x] [js](https://github.com/meilisearch/meilisearch-js/pull/562)
- [x] [php](https://github.com/meilisearch/meilisearch-php/pull/80)
- [x] [ruby](https://github.com/meilisearch/meilisearch-ruby/pull/82)
- [x] swift

---- WIP

- [ ] dotnet?
- [ ] java?
- [ ] rust?

**Comment by curquiza** [comment]
All the packages tests are up to date and runs with the v0.15!
