### ISSUE TITLE
Bump MeiliSearch v0.15.0

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#43]
# HTTP changes in new MeiliSearch release

Feel free to check the boxes if the changes do not apply to the suggested SDK.

## Facet Distributions changes
<s>Link: meilisearch/MeiliSearch#944

Routes impacted: 
- `facetsDistribution` in a search query `/indexes/test/search?facetsDistribution=%5B%22color%22%5D`

**This apply only to SDKs that made specific tests on facetDistributions** should test if they are not breaking with the new MeiliSearch version.</s>

**This PR has been reverted**

## Fields are now sorted with consistency

<s>Link: Sort fields without consistency in lexicographical order meilisearch/MeiliSearch#943

Routes impacted: 
- `displayedAttributes` in `GET /index/:uid:/settings` and `GET /index/:uid:/settings/displayed-attributes` routes
- `facetsDistribution` in a search query `/indexes/test/search?facetsDistribution=%5B%22color%22%5D`
SDK's that used to "sort" the return of MeiliSearch before making the test should remove the sort function.

**This impact only SDKs that still have tests that sorts responses from MeiliSearch**</s>

**This issue is not ready for this version**

## Remove update health

<s>Link: Refactor /health route meilisearch/MeiliSearch#940

The update health route should be removed from every SDK</s>

**This issue is not ready for this version**

## Dumps (old name: Backups)
link:  Dump Meilisearch DataBase triggering an HTTP route meilisearch/MeiliSearch#840 & dump meilisearch/MeiliSearch#887

cf #44 

## Lazely create an index

<s>// Will be discussed in another issue</s>

**This issue is not ready for this version**

## Empty string returns placeholer search

link: Considere an empty query search as a placeholder search meilisearch/MeiliSearch#916

**For SDKs that tested an empty string as a query** to verify that MeiliSearch returns an empty string, tests must be changed.

SDKs:
- [x] meilisearch-go
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [x] meilisearch-swift
- [ ] meilisearch-rust
- [ ] meilisearch-java
- [x] meilisearch-net
- [x] instant-meilisearch
- [x] docs-searchbar.js
- [x] vuepress-plugin-meilisearch

**Comment by curquiza** [comment]
I updated the issue according to the [pre-release content](https://github.com/meilisearch/MeiliSearch/milestone/11?closed=1).

Moral of the story: not to create this kind of issue until the pre-release is out 😂

**Comment by bidoubiwa** [comment]
Absolutely, point taken haha 😂

**Comment by curquiza** [comment]
I'm closing this issue since all the SDKs handle placeholder search and the dumps issues have been created in the remaining repositories that do not integrate the dumps yet. The dumps feature in the SDKs is indeed a not-emergency feature.
