### ISSUE TITLE
Implement dumps routes in SDKs

### ISSUE THREAD

**Issue by eskombro** [meilisearch/integration-guides#44]
MeiliSearch [v0.15.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0) adds `dumps` functionality, implemented in:

- https://github.com/meilisearch/MeiliSearch/pull/887
- https://github.com/meilisearch/MeiliSearch/pull/982

> Dumps were previously named `backups`

In order to provide access to this functionality from SDKs, they need to implement 2 new routes, and update the code samples:

# 1. New Routes

#### Example

To start the creation of a dump, a request must be sent as follows:

```curl
curl -X POST "http://localhost:7700/dumps"
```

#### Response (SUCCESS)

If the creation of a dump is accepted, the HTTP status code `202` will be received and a `uid` in the json body will inform the user of the unique identifier of the dump that is being created.

```bash
HTTP/1.1 202 Accepted
content-encoding: gzip
content-type: application/json
date: Tue, 06 Oct 2020 05:32:43 GMT
transfer-encoding: chunked
```
```json
{
    "status": "processing",
    "uid": "20201006-053243949"
}
```

#### Response (ERROR)

```bash
HTTP/1.1 409 Conflict
content-encoding: gzip
content-type: application/json
date: Tue, 06 Oct 2020 05:42:36 GMT
transfer-encoding: chunked
```
```json
{
    "errorCode": "dump_already_in_progress",
    "errorLink": "https://docs.meilisearch.com/errors#dump_already_in_progress",
    "errorType": "invalid_request_error",
    "message": "Another dump is already in progress"
}
```

### 1.2. Get a `dump` creation status, using the `/dumps/<dump-uid>/status` route.

If the user needs to know the status of it's dump creation, a request must be sent as follows:

`curl -X GET "http://localhost:7700/dumps/<dump-uid>/status"`

#### Response

```bash
HTTP/1.1 200 OK
content-encoding: gzip
content-type: application/json
date: Tue, 06 Oct 2020 05:48:00 GMT
transfer-encoding: chunked
```
```json
{
    "status": "done",
    "uid": "20201006-054235910"
}
```

# 2. Update code samples

All `code-samples` should be updated and added the following examples in their respective language: 

```yaml
post_dump_1: |- 
  $ curl -X POST 'http://localhost:7700/dumps'
get_dump_status_1: |- 
  $ curl -X GET 'http://localhost:7700/dumps/20201101-110357260/status'
```

# IMPLEMENTATION EXAMPLE

- *Routes*: [example](https://github.com/meilisearch/meilisearch-python/blob/master/meilisearch/client.py#L180-L207)
- *Tests*: [example](https://github.com/meilisearch/meilisearch-python/blob/master/meilisearch/tests/client/test_client_dumps.py)
- *Code samples*: [example](https://github.com/meilisearch/meilisearch-python/blob/master/.code-samples.meilisearch.yaml#L364-L367)

# PROGRESS

SDKs:
- [ ] [meilisearch-go](https://github.com/meilisearch/meilisearch-go/issues/82)
- [x] [meilisearch-js](https://github.com/meilisearch/meilisearch-js/issues/626)
- [x] [meilisearch-php](https://github.com/meilisearch/meilisearch-php/pull/106)
- [x] [meilisearch-python](https://github.com/meilisearch/meilisearch-python/pull/157)
- [x] [meilisearch-ruby](https://github.com/meilisearch/meilisearch-ruby/issues/101)
- [x] [meilisearch-swift](https://github.com/meilisearch/meilisearch-swift/pull/72)
- [ ] [meilisearch-rust](https://github.com/meilisearch/meilisearch-rust/issues/54)
- [x] [meilisearch-dotnet](https://github.com/meilisearch/meilisearch-dotnet/issues/69)
- [ ] [meilisearch-java](https://github.com/meilisearch/meilisearch-java/issues/35)

**Comment by bidoubiwa** [comment]
All `code-samples` should be updated and added the following examples in their respective language: 

```yaml
post_dump_1: |- 
  $ curl -X POST 'http://localhost:7700/dumps',
get_dump_status_1: |- 
  $ curl -X GET 'http://localhost:7700/dumps/:dump_uid/status',
```

**Comment by eskombro** [comment]
I added your code samples comment to the issue description @bidoubiwa  !

**Comment by bidoubiwa** [comment]
I will need some other code-sample I just realize. As soon as the guide is finished I will add the missing code-samples and validate this issue. Is that oke for you?

**Comment by eskombro** [comment]
> Is that oke for you?

That is oke for me! :)

**Comment by bidoubiwa** [comment]
This is the final code-sample:
```
post_dump_1: |-
  $ curl -X POST 'http://localhost:7700/dumps'
get_dump_status_1: |-
  $ curl -X GET 'http://localhost:7700/dumps/20201101-110357260/status'
```

None have been added because they were more `cli` options than `http` once. But @curquiza changed the second one by adding a real dump_uid.

**Comment by eskombro** [comment]
> This is the final code-sample:
> 
> ```
> post_dump_1: |-
>   $ curl -X POST 'http://localhost:7700/dumps'
> get_dump_status_1: |-
>   $ curl -X GET 'http://localhost:7700/dumps/20201101-110357260/status'
> ```
> 
> None have been added because they were more `cli` options than `http` once. But @curquiza changed the second one by adding a real dump_uid.

Juste pour etre sur, on laisse carrement `/dumps/20201101-110357260/status` avec cet uid concret?

**Comment by eskombro** [comment]
Great, after [this](https://github.com/meilisearch/meilisearch-python/pull/157#pullrequestreview-507636039) is approved, I'll update this issue with an example (python) and create issues in the repositories that haven't implemented dumps yet 👍

**Comment by curquiza** [comment]
I close this issue since all the issues are opened in the repositories that don't have this feature implemented yet.
