### ISSUE TITLE
Implement telemetry in MeiliSearch integrations

### ISSUE THREAD

**Issue by tpayet** [meilisearch/integration-guides#45]
Hello! 

We have more and more usage of our SDKs and integrations. In order to gauge feature usage in these different libraries, MeiliSearch could use some anonymously collected telemetry data. 

Using this information, we would be able to measure:
- the usage of each SDK
- the usage of the different methods
- which features are used or not
- what are the bugs and when do they happen

We shall use a different platform for telemetry and bug report. For bug report, Sentry seems to be the obvious choice. We should check if it's possible to configure Sentry to work for our libraries and not for the whole binaries they are used in.

For telemetry, there are several options that I will begin to benchmark: Posthog, Amplitude, Segment, or any other tools you might suggest!

The telemetry should be disableable as easily as in MeiliSearch ([using an ENV variable](https://docs.meilisearch.com/guides/advanced_guides/configuration.html#analytics)).

What do you think? Is there anything you think we should track in order to better understand the users?

**Comment by eskombro** [comment]
I have read this issue, and it is a very interesting discussion but also could be a bit sensitive. I have to say that I struggle to find a clear position myself on if we should add this by deafult, or just make it possible to be activated, and ask politely the developers to activate it to helps teh development process (which will of course create not-representative and not-raliable data, but coming form people who actively want to share it).

**Comment by curquiza** [comment]
We are going to start with using user-agent header and sending it to MeiliSearch server as suggested here: https://github.com/meilisearch/integration-guides/issues/58

This way:
- we can use the already implemented analytics in MeiliSearch, which is easier for a first MVP.
- if the users want to desable analytics, there is only one step to do (desable analytics for MeiliSearch)
