### ISSUE TITLE
Bors and bumps

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#46]
When merging bump at the start of the week `bors` raises the following error: 

```
{{:badmatch,
  {:error, :push, 422,
   "{\"message\":\"At least 1 approving review is required by reviewers with write access.\",\"documentation_url\":\"https://docs.github.com/articles/about-protected-branches\"}"}},
```

Is this something that we want? Something that can be changed?

**Comment by curquiza** [comment]
What don't you want in this behavior?
Why do you try to merge an unapproved PR?

**Comment by curquiza** [comment]
Merge an un-approved PR is an administrator privilege and should not be done in most cases. Bors can be launched by a write-access contributor. So, if Bors could apply changes that only an admin contrib could, it would be a HUGE problem 🙂

**Comment by bidoubiwa** [comment]
My bad
