### ISSUE TITLE
Changes related to MeiliSearch bump to v0.16.0

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#52]
The changes related to the new MeiliSearch bump, see the [related milestones](https://github.com/meilisearch/MeiliSearch/milestone/13?closed=1).

# To do before the release

Here are the "emergency" changes to code before releasing MeiliSearch.

## Remove the `PUT /health routes`

For SDKs providing a method for this route, we should remove it:
- in the code
- in the tests
- in the code-samples, if there are present.

## Dumps changes

These changes might impact some test suites but not the code-base itself.

## Sort `displayedAttributes` fields

These changes might impact some test suites but not the code-base itself.

# Could be done after the release

The following section is not a emergency change, but could be done before releasing MeiliSearch if you find some times to do it.
⚠️ The priority is still given to the described changes above.

## Implicit index creation

Please refer to this more detailed issue #48.

**Comment by bidoubiwa** [comment]
The dataset of MeiliSearch has now officially replaced all `genre` field with `genres`. After a quick peek inside some code-samples I can see `genre` fields are still present. Could we add the check of `genre` field inside the code-samples to the changes related to the v0.16 or do we create a different issue for this ?

**Comment by curquiza** [comment]
The mandatory part is done and merged to all the SDKs.

**Comment by curquiza** [comment]
I close this one, since #48 is still open and corresponds to the part that is not finished.
