### ISSUE TITLE
Analytics for integrations

### ISSUE THREAD

**Issue by qdequele** [meilisearch/integration-guides#58]
Set il all SDK and integration as user agent for help to know the sdk usage. Keep the default user agent and add our own. 

For example: `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15 MeiliSearchReact/0.16.0`. 
Composed: MeiliSearch+SDK/Version.

**Comment by curquiza** [comment]
Just to be sure about what you expect:

What you want for `meilisearch-go` would be: `User-Agent: MeiliSearchGo/v0.13.1`
And what you want for a front-end tool, like `instant-meilisearch`: `User-Agent: InstantMeiliSearch/v0.2.3 MeiliSearchJS/v0.16.0`

**Comment by curquiza** [comment]
We are taking note of this request, we will write here what we exactly expect before any approval + implementation 🙂

**Comment by curquiza** [comment]
@gmourier and I are working on it here, since it also concerns implementation in the core: https://github.com/meilisearch/product/issues/168

**Comment by curquiza** [comment]
A spec integrating the `User-Agent` header is in progress so that the integration team can pass information through this header: https://github.com/meilisearch/specifications/pull/84

**Comment by curquiza** [comment]
Replaced by #150
