### ISSUE TITLE
meilisearch-postgresql

### ISSUE THREAD

**Issue by acc557** [meilisearch/integration-guides#62]
There is a[ rust-based plugin for postgresql ](https://github.com/zombodb/zombodb) to use elasticsearch as index for full text-search 

I have been using this plugin and meilisearch for a while, and I think it will be very interesting if they can  be combined, maybe into a meilisearch-postgresql plugin.

**Comment by curquiza** [comment]
Closing this issue in favor of #20

**Comment by curquiza** [comment]
Just realized I've misunderstood your suggestion @acc557, sorry about this!
Your suggestion is more related to #71.
