### ISSUE TITLE
Add a link to this repo on each SDKs README

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#7]
This repository and the integration guidelines should be more visible in the SDKs README so that the contributors can see them if they want to create their own one.

### Steps

- [x] [JS](https://github.com/meilisearch/meilisearch-js/issues/373)
- [x] [PHP](https://github.com/meilisearch/meilisearch-php/issues/31)
- [x] [Laravel](https://github.com/meilisearch/meilisearch-laravel-scout/issues/21)
- [x] [Swift](https://github.com/meilisearch/meilisearch-swift/issues/9)
- [x] [Ruby](https://github.com/meilisearch/meilisearch-ruby/issues/32)
- [x] [Go](https://github.com/meilisearch/meilisearch-go/issues/19)
- [x]  [Python](https://github.com/meilisearch/meilisearch-python/issues/68)
- [x] [DigitalOcean](https://github.com/meilisearch/meilisearch-digital-ocean/issues/36)
- [x] Vuepress
- [x] [docs-scraper](https://github.com/meilisearch/docs-scraper/issues/18)
- [x] docs-searchbar.js
- [x] .NET

Later:
- [ ] Java (when it will be finished)
- [ ] Rust (when it will be finished)

### Final suggestion:

To copy/past and to put at the end of the repositories.

```
<hr>

**MeiliSearch** provides and maintains many **SDKs and Integration tools** like this one. We want to provide everyone with an **amazing search experience for any kind of project**. If you want to contribute, make suggestions, or just know what's going on right now, visit us in the [integration-guides](https://github.com/meilisearch/integration-guides) repository.
```

**Comment by eskombro** [comment]
That is a very good idea. I can do Python and Go! (making an issue in the repos and assigning myself)

**Comment by eskombro** [comment]
I can do the rest, but got to have access to all of them ;)

**Comment by curquiza** [comment]
@eskombro could you make a suggestion of what kind of sentence you think about writing before doing any PR? 🙂

Plus you don't need any access to add an issue in the other repos or to do this kind of PR 🙃

I would rather do it for all the SDKs in the same, since it's a quick task, and not isolate some of them.

**Comment by eskombro** [comment]
My first suggestion ;)
```
MeiliSearch provides and maintain many **SDKs and Integration tools**. Our goal is to make it easy for everyone to have **an amazing search on any kind of project**. If you want to contribute, make suggestions or just know what's going on right now, visit us in the [integration-guides](https://github.com/meilisearch/integration-guides) repository
```

**Comment by bidoubiwa** [comment]
Great suggestion!  This message would be at the end of the readme?

**Comment by eskombro** [comment]
> Great suggestion! This message would be at the end of the readme?

Sorry, @bidoubiwa. That's the idea, it would be the footer of the readme. So last lines. What do you think?

**Comment by bidoubiwa** [comment]
Great I approve!

**Comment by bidoubiwa** [comment]
Yes, great I approve!

**Comment by eskombro** [comment]
🚀?

**Comment by eskombro** [comment]
Today I added this footer to all of our repos (listed in the description).

For the repos I can't update (access/premissions), I created an issue/pr:

[swift](https://github.com/meilisearch/meilisearch-swift/pull/10)
[docs-scraper](https://github.com/meilisearch/docs-scraper/pull/19)
[laravel](https://github.com/meilisearch/meilisearch-laravel-scout/issues/21) Already merged by https://github.com/shokme

@curquiza can you merge?

**Comment by curquiza** [comment]
Done!
I let the issue open for the new comers (Java, Rust, and maybe... Elixir!!!)

**Comment by curquiza** [comment]
Done on the rust! Java is still a WIP! Closing this issue now all the SDKs have the same README template
