### ISSUE TITLE
Guides clarification

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#76]
# Pre-release week guide
[here](https://github.com/meilisearch/integration-guides/blob/master/guides/pre-release-week.md)

## Testing
> Test manually the RC with a Core team member or on your own. Should be done by all the Integration team members.

Is this an official new step?

> Run all the SDKs automatic test suites against the RC thanks to this script. If tests are not green, these should be justified.

Should we launch those tests on multiple environments (Mac, linux, windows)? 

## Coding 

> Create a PR up-to-date with bump-meilisearch-v*.*.* and pointing to bump-meilisearch-v*.*.* with all the changes.

Is this the same as what is written in `first preparations` ?
> In each integration repository, create a draft PR modifying the old version of MeiliSearch into the future release version. The branch name originating this PR should be bump-meilisearch-v*.*.*. In most cases, only the README.md file changes.

**Comment by curquiza** [comment]
> > Test manually the RC with a Core team member or on your own. Should be done by all the Integration team members.
> 
> Is this an official new step?

Nope, we already do it. Sam do it with Marin, and we (you and me) do it on our own.




> Run all the SDKs automatic test suites against the RC thanks to this script. If tests are not green, these should be justified.

For the moment I run it on my machine (MacOS). I plan to do it in a CI, so on Linux (and MacOS for swift).
Testing MeilISearch works in different environments is not our scope from my POV.

> Create a PR up-to-date with bump-meilisearch-v*._._ and pointing to bump-meilisearch-v*._._ with all the changes.

Yes, it's the same pre-release week, so the same release tag.


> In each integration repository, create a draft PR modifying the old version of MeiliSearch into the future release version. The branch name originating this PR should be bump-meilisearch-v*._._. In most cases, only the README.md file changes.

You did not put any question 😆

**Comment by bidoubiwa** [comment]
It is the text after the title: `firt preparations` in the guide. It was to bring context to the previous question

**Comment by curquiza** [comment]
Do you need any change or precision after my first return?
Or can I close the issue?

**Comment by bidoubiwa** [comment]
No thanks it clear !
