### ISSUE TITLE
Gatsby Plugin

### ISSUE THREAD

**Issue by tobyglei** [meilisearch/integration-guides#83]
- **Is your feature request related to a problem? Please describe.**

It's feature and docs request.

I'm the founder of [21YunBox](https://www.21yunbox.com/), we provide blazing fast Chinese CDN, continuous deployment, one-click HTTPS and other services like managed databases and backend web services, providing an avenue to launch web projects in China. 

We have recently received a lot of requests about Algolia alternatives because Algolia doesn't work in China due to the [Great Firewall](https://en.wikipedia.org/wiki/Great_Firewall). So MeiliSearch is the go-to solution for them now, but it's lack of good docs and guides with Gatsby and other web frameworks like Next.js and Jekyll. This makes it difficult for users to migrate.

- **Describe the solution you'd like**

We hope to see:
1. MeiliSerach plugin with Gatsby, like this [https://github.com/algolia/gatsby-plugin-algolia](https://github.com/algolia/gatsby-plugin-algolia)
2. Docs and guide to migrate and get started with Gatsby and other web frameworks like this [https://www.gatsbyjs.com/docs/adding-search-with-algolia/](https://www.gatsbyjs.com/docs/adding-search-with-algolia/)

- **Describe alternatives you've considered**
na

**Comment by tobyglei** [comment]
Nice. Let me know when you guys have a roadmap for the Gatsby plugin.

I'm also writing a blog about "a step by step guide to deploy MeiliSearch in China", it will be up live in the next couple of days so developers know how to deploy MeiliSearch easily, it will be great if you guys can include it on your docs (https://docs.meilisearch.com/), let me know where to put it.

**Comment by curquiza** [comment]
@tobyglei, that's great!
Maybe @fharper could help/guide you with the article? 🙂

**Comment by fharper** [comment]
@tobyglei not sure if you are the only who sent me an email about a blog post, but if not, please feel free to send me a draft if you want us to review the content. My email is fred  @ meilisearch.com .

As for where we could link your article, I'll let @react-learner decided. He is the one managing our documentation.

**Comment by tobyglei** [comment]
Thanks @curquiza and @fharper 

Here is the blog post: https://www.21yunbox.com/blog/solutions/algolia-alternatives-in-china.html

As for the docs, @react-learner do you have any idea where to put it?

**Comment by react-learner** [comment]
@tobyglei Thanks for the suggestion, and for writing this article! 😄 

Unfortunately, our documentation is monolingual (English) right now. I believe that is something we want to change in the future, but for the moment we lack the technology + staff to support multiple versions of the docs.

However, we have been thinking for a while that it would be nice to have a spot on the documentation site where we highlight excellent content, tools, etc. from around the community (https://github.com/meilisearch/documentation/issues/681 , https://github.com/meilisearch/documentation/issues/691). It's not currently a priority, but if it does happen then could we add your blog post there?

**Comment by tobyglei** [comment]
@react-learner 

The extra resource idea is great!

Agree with the consistency. I guess it's better to have a "deployment" section on your docs, so we can create something similar to [this](https://www.gatsbyjs.com/docs/deploying-to-21yunbox/) for your users.

**Comment by fharper** [comment]
On my side I shared the blog post with our communities:
- https://twitter.com/meilisearch/status/1354890218906800132
- https://www.linkedin.com/feed/update/urn:li:activity:6760656387413434368
- and our Slack Community

Thanks again for writing it!

**Comment by tobyglei** [comment]
@fharper thanks for sharing it. 

We just recevied few other developers/startups interested in switching to MeiliSearch since the blogs went live couple days ago. They are indeed waiting for the Gatsby plugin to do the switch. Looking forward to hearing about the updates on Gatsby Plugin.

Thanks guys!

**Comment by tobyglei** [comment]
hey guys, do you have a roadmap / updates on the Gatsby plugin? I have few users asked me this, and I don't have an answer for them yet. 

If you guys have things plan out already, let me know so I can tell my users what and when to expect to see Gatsby Plugin working.

**Comment by curquiza** [comment]
Hey @tobyglei
We are not planning to work on this for Q1 and Q2 is not planned yet. This is something we have on our mind but are not able to prioritize yet. We have a React integration though which should be fairly simple to integrate within a Gatsby app. 
We would be glad to help someone getting started to work on this as we are always keen to support our contributors.

**Comment by tobyglei** [comment]
@curquiza 
Sure, I will let them know, in the meantime (while they are waiting), do you have some sample code snippets that I can quickly share with them as a temporary solution?

**Comment by curquiza** [comment]
We have nothing to replace a Gatsby integration for the moment. However @bidoubiwa created a quick start that might help you: https://github.com/bidoubiwa/gatsby-meilisearch-example

**Comment by tobyglei** [comment]
@curquiza Nice, this is a good starting point so I can include it on my docs.

**Comment by curquiza** [comment]
@mdubus is starting it next week 🎉

**Comment by brunoocasali** [comment]
Hey @tobyglei, an official release of our Gatsby Plugin was released Jan/2022 :)

Check it out: https://github.com/meilisearch/gatsby-plugin-meilisearch
