### ISSUE TITLE
WIP - Discussion about README template

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#9]
I just start to group all the remarks I got thanks to contributors and after our meetings:

### Examples

- <s>Add examples about filtering ([PR on PHP SDK](https://github.com/meilisearch/meilisearch-php/pull/20)): indeed, filters are a demanding feature and not easy to handle. Other examples about custom search, in general, could be a good idea, especially for the SDK JS</s> => we plan to remove the Examples section once all the examples are integrated to the main docs.
- <s>Add examples to use settings</s> => same than above
- Add examples about custom method relative to the SDK only? => see #27 

### Contributions

- <s>Add a contributors section?</s>
- <s>Add a `CONTRIBUTING.md` -> related to [this discussion](https://github.com/meilisearch/discuss/discussions/25#discussioncomment-8563).</s>

Done in #33 

### The table of Contents

Having a TOC in a README is really useful but is a pain to maintain. The best way is to generate it automatically.
We could enforce the user to use (so to install) tool like [doctoc](https://github.com/thlorenz/doctoc) and to run it before submitting it.
-> A script could check that the TOC is up-to-date for each PR.
-> in the README, the TOC could be surrounded by comments `Do not change manually, use doctoc instead` (for example).

### Future!!

We should automatize PR on README to avoid opening manually a PR for each SDK for each change.

**Comment by erlend-sh** [comment]
> A collaborator section?

I think we should have a standard, project-wide way of listing contributors/collaborators. I've started a topic about it on our internal board.

**Comment by curquiza** [comment]
Our READMEs now contain this different sections

What we expect about READMEs is described here: https://github.com/meilisearch/integration-guides/blob/main/guides/build-integration.md#2-readme

> We should automatize PR on README to avoid opening manually a PR for each SDK for each change.

Done with meili-bot
