### ISSUE TITLE
Search method to send multiple search request

### ISSUE THREAD

**Issue by curquiza** [meilisearch/integration-guides#91]
To manage front-end display of facets and range sliders, MeiliSearch needs to perform multiple searches.

For the moment, contrary to the Algolia search engine, there is no way to send multiple requests of search in the same HTTP call. Thus, we need to send multiple HTTP calls to get the same result.

However, for a better user experience we should create a method to apply this in our SDK:

```text
function multipleSearch(array searchParameters) -> array searchAnswers
```

This method will take as a parameter an array of the search objects. These objects will contain the search parameters (including the `q`).
The return will be an array of the MeiliSearch answer objects, corresponding to the different search requests, so the order should be the same.

⚠️ We all know this method will not be optimized: an array of 4 requested would mean 4 HTTP calls! However, this is currently the only way to manage this kind of front-end issue. So providing the method would at least help in terms of coding experience if the developer definitely needs this feature.
Plus, MeiliSearch will integrate a way to send multiple requests in one HTTP call in the future, so the method would already be ready.

## Todo

We need to test this kind of method in the most used repos for front-end, so meilisearch-js (to apply it into instant-meilisearch).
Then we could do the implementation in meiliserach-php, ruby, python... (other languages used in famous web frameworks)

**Comment by brunoocasali** [comment]
I came from the future, and I can say this will be implemented very soon!

See the following issue: https://github.com/meilisearch/meilisearch/issues/3427

Since this will be present in the central issue for v1.1 or maybe v1.2, I don't think we should keep this open, let me know if I'm wrong!
