### ISSUE TITLE
When releasing a new breaking version of a package, could we start with a beta tag instead of latest ?

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#93]
At the moment, when releasing on the package manager a new breaking version it automatically goes to `latest` tag. 
I was wondering if we could, when the situations call for it, first use an intermediary tag to further test implementations in other repos.

For exemple, how angular-instantsearch has handled it: https://classic.yarnpkg.com/en/package/angular-instantsearch

<img width="423" alt="Screenshot 2021-02-11 at 15 03 42" src="https://user-images.githubusercontent.com/33010418/107646524-59014f00-6c7a-11eb-97ab-9192a63c441b.png">

**Comment by eskombro** [comment]
I think this will be a good approach after v1 for every minor, but not for patches and fixes, so I wouldn't introduce this just now, but later I would really like it! :)

**Comment by curquiza** [comment]
Yes, this is a good idea, once we will release stable versions of our integrations. For the moment, it's too much I think 🙂

**Comment by bidoubiwa** [comment]
Oke! I understand your point of view. Sometimes I'm a bit afraid that my packages wont work with another project (which should not happen with the tests of course). But with a beta tag I could try them out without having to `npm pack` everywhere.

Nonetheless, it would make more sense after v1
