### ISSUE TITLE
Add contributors automatically

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#94]
While browsing on a project I stumbled upon this pull request: 

https://github.com/alexzaganelli/strapi-plugin-email-designer/pull/1

They apparently use this tool: https://github.com/apps/allcontributors
which states: 

> The @all-contributors bot automatically adds contributor acknowledgements according to the all-contributors specification ✨

You have to use their tool the following way to add the user:
```
@all-contributors please add @jakebolam for infrastructure, tests and code
```

For the example mentionned above, they are automatically added to the bottom of the readme like so:

<img width="917" alt="Screenshot 2021-02-15 at 16 12 01" src="https://user-images.githubusercontent.com/33010418/107963527-93375d00-6fa8-11eb-899f-774344b6f86a.png">

I thought this could be a really good thing to implement! I would like your opinion on it and if you agree how would you like to add contributors?

**Comment by fharper** [comment]
It's in our Q1 plan :D

https://github.com/meilisearch/devrel/issues/89

**Comment by curquiza** [comment]
Looking forward to integrating this, thanks @fharper!
I close this issue since it's in the dev rel scope and planned for the Q1 🎉
