### ISSUE TITLE
Do not add $ preceeding bash command on code examples

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#99]
We have a consistent manner to add a dollar sign in front of each bash command on our getting started. 

These have already been changed in the documentation as they were copied when using the clipboard plugin. I have given a bit of thought on the subject and based on my experience of having to remove manually the $ sign from my copies multiple times a week, I was wondering how our competitors might approach this.

I could not find examples of basic bash commands with a `$` sign but I found some when the output of the bash command is explicitly shown:

**I have looked at more than 15 repos here are some well known**

### Example twilio
<img width="473" alt="Screenshot 2021-02-23 at 14 08 05" src="https://user-images.githubusercontent.com/33010418/108848125-e29d0f00-75e0-11eb-87e4-5311bcaeb8da.png">

### Example instantsearch

<img width="456" alt="Screenshot 2021-02-23 at 14 07 13" src="https://user-images.githubusercontent.com/33010418/108848137-e761c300-75e0-11eb-9ffa-ce286e698e94.png">

### Example Commander (cli tool)

[Commander](https://github.com/tj/commander.js#readme) when explicit output is shown: 
<img width="377" alt="Screenshot 2021-02-23 at 14 09 37" src="https://user-images.githubusercontent.com/33010418/108848158-ee88d100-75e0-11eb-86ff-1b5536e51eda.png">

It is really hard to find example of multiples cmd in the same code block. I found one in [mongo installation](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/), but most of the commands are in a separate code block
### Example Mongo Installation
<img width="790" alt="Screenshot 2021-02-23 at 14 18 12" src="https://user-images.githubusercontent.com/33010418/108849019-feed7b80-75e1-11eb-9b0c-01059495da97.png">

<img width="583" alt="Screenshot 2021-02-23 at 14 19 53" src="https://user-images.githubusercontent.com/33010418/108849234-38be8200-75e2-11eb-99ff-a54d1d6302e2.png">

### Example Strip ruby 

<img width="302" alt="Screenshot 2021-02-23 at 14 11 31" src="https://user-images.githubusercontent.com/33010418/108848316-23952380-75e1-11eb-871c-ca65b4826efe.png">

## Conclusion
What I conclude from that is, if we think the user might want to copy/paste every command, then we should put them all in a separate code block. If the commands are just a showcase that will mostly not be copy/paster, we add them in the same code-block.

- Break down code block with multiple important commands into multiple code block without a preceding `$`
- Leave `$` on bash examples with a clear intention of showing the output of the code block
- No specific rules for `$` when multiple non-important command lines are written one after the other. We could say yes by default. But again this limits the user that wants to copy/paste in a bash script.

**Comment by sanders41** [comment]
For what it's worth [this](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md014) is the markdownlint recommendation on the $.

**Comment by bidoubiwa** [comment]
This is a really really good reference. Thanks a lot @sanders41. It might settle this issue more easily 😄

**Comment by curquiza** [comment]
Thanks @sanders41 for the reference!
Indeed, we should remove the `$` when the copy/paste context is obvious!

**Comment by bidoubiwa** [comment]
fixed by #103
